# Generated by Django 5.2.13 on 2026-05-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(default='PR', max_length=2)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['uf', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(blank=True, max_length=50)),
                ('categoria_cnh', models.CharField(blank=True, max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='cadastros.unidade'),
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('combustivel', models.CharField(blank=True, max_length=120)),
                ('ativa', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas', to='cadastros.unidade')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['placa'],
            },
        ),
    ]
