# Generated by Django 5.2.13 on 2026-05-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_motorista_options_cidade_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='ativa',
        ),
        migrations.AlterField(
            model_name='servidor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='cadastros.unidade'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='cadastros.unidade'),
        ),
    ]
