# Generated by Django 5.2.13 on 2026-05-04 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _normalize_existing_data(apps, schema_editor):
    Servidor = apps.get_model("cadastros", "Servidor")
    Viatura = apps.get_model("cadastros", "Viatura")

    for servidor in Servidor.objects.all():
        servidor.nome = " ".join((servidor.nome or "").strip().split()).upper()
        servidor.cpf = "".join(c for c in (servidor.cpf or "") if c.isdigit())[:11]
        servidor.save(update_fields=["nome", "cpf"])

    for viatura in Viatura.objects.all():
        viatura.placa = "".join(c for c in (viatura.placa or "").upper() if c.isalnum())[:7]
        viatura.save(update_fields=["placa"])


def _map_relations(apps, schema_editor):
    Cargo = apps.get_model("cadastros", "Cargo")
    Combustivel = apps.get_model("cadastros", "Combustivel")
    Servidor = apps.get_model("cadastros", "Servidor")
    Viatura = apps.get_model("cadastros", "Viatura")

    for servidor in Servidor.objects.all():
        cargo_nome = " ".join((getattr(servidor, "cargo_legacy", "") or "").strip().split()).upper()
        if cargo_nome:
            cargo, _ = Cargo.objects.get_or_create(nome=cargo_nome)
            servidor.cargo_temp_id = cargo.id
            servidor.save(update_fields=["cargo_temp"])

    for viatura in Viatura.objects.all():
        combustivel_nome = " ".join((getattr(viatura, "combustivel_legacy", "") or "").strip().split()).upper()
        if combustivel_nome:
            combustivel, _ = Combustivel.objects.get_or_create(nome=combustivel_nome)
            viatura.combustivel_temp_id = combustivel.id
            viatura.save(update_fields=["combustivel_temp"])


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_remove_cidade_ativa_remove_motorista_ativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Combustivel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Combustível",
                "verbose_name_plural": "Combustíveis",
                "ordering": ["nome"],
            },
        ),
        migrations.RenameField(model_name="servidor", old_name="cargo", new_name="cargo_legacy"),
        migrations.RenameField(model_name="viatura", old_name="combustivel", new_name="combustivel_legacy"),
        migrations.AddField(
            model_name="servidor",
            name="cargo_temp",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cadastros.cargo"),
        ),
        migrations.AddField(
            model_name="viatura",
            name="combustivel_temp",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cadastros.combustivel"),
        ),
        migrations.RunPython(_normalize_existing_data, migrations.RunPython.noop),
        migrations.RunPython(_map_relations, migrations.RunPython.noop),
        migrations.RemoveField(model_name="servidor", name="matricula"),
        migrations.RemoveField(model_name="viatura", name="marca"),
        migrations.RemoveField(model_name="viatura", name="unidade"),
        migrations.AddField(model_name="servidor", name="rg", field=models.CharField(blank=True, max_length=20)),
        migrations.AlterField(model_name="servidor", name="cpf", field=models.CharField(blank=True, max_length=11)),
        migrations.AlterField(model_name="servidor", name="nome", field=models.CharField(max_length=255, unique=True)),
        migrations.AlterField(model_name="viatura", name="placa", field=models.CharField(max_length=7, unique=True)),
        migrations.AlterField(
            model_name="viatura",
            name="tipo",
            field=models.CharField(blank=True, choices=[("CARACTERIZADA", "Caracterizada"), ("DESCARACTERIZADA", "Descaracterizada")], max_length=20),
        ),
        migrations.RemoveField(model_name="servidor", name="cargo_legacy"),
        migrations.RemoveField(model_name="viatura", name="combustivel_legacy"),
        migrations.RenameField(model_name="servidor", old_name="cargo_temp", new_name="cargo"),
        migrations.RenameField(model_name="viatura", old_name="combustivel_temp", new_name="combustivel"),
        migrations.AlterField(
            model_name="servidor",
            name="cargo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="servidores", to="cadastros.cargo"),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="combustivel",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="viaturas", to="cadastros.combustivel"),
        ),
        migrations.DeleteModel(name="Motorista"),
    ]
