# Generated by Django 5.2.13 on 2026-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cargo_combustivel_remove_servidor_matricula_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('nome', 'uf'), name='unique_cidade_nome_uf'),
        ),
    ]
