# Generated by Django 5.2.13 on 2026-05-04 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _popular_estado_em_cidades(apps, schema_editor):
    Estado = apps.get_model("cadastros", "Estado")
    Cidade = apps.get_model("cadastros", "Cidade")
    ufs = Cidade.objects.order_by().values_list("uf", flat=True).distinct()
    sigla_to_pk = {}
    for raw in ufs:
        sigla = (raw or "").strip().upper()[:2]
        if len(sigla) != 2:
            continue
        estado, _ = Estado.objects.get_or_create(
            sigla=sigla,
            defaults={"nome": sigla, "codigo_ibge": None},
        )
        sigla_to_pk[sigla] = estado.pk
    for cidade in Cidade.objects.iterator():
        sigla = (cidade.uf or "").strip().upper()[:2]
        if sigla in sigla_to_pk:
            cidade.estado_id = sigla_to_pk[sigla]
            cidade.save(update_fields=["estado_id"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_cidade_unique_nome_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=128)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('codigo_ibge', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['estado__sigla', 'nome'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.RemoveConstraint(
            model_name='cidade',
            name='unique_cidade_nome_uf',
        ),
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_estado_nome'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='cadastros.estado'),
        ),
        migrations.RunPython(_popular_estado_em_cidades, _noop_reverse),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('nome', 'estado'), name='unique_cidade_nome_estado'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_ibge__isnull', False)), fields=('codigo_ibge',), name='unique_cidade_codigo_ibge_nn'),
        ),
    ]
