# Generated by Django 5.2.13 on 2026-05-04 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_cidade_estado_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('OFICIO', 'Ofício'), ('JUSTIFICATIVA', 'Justificativa'), ('PLANO_TRABALHO', 'Plano de Trabalho'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('TERMO_AUTORIZACAO', 'Termo de Autorização')], max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Assinatura (configuração)',
                'verbose_name_plural': 'Assinaturas (configuração)',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prazo_justificativa_dias', models.PositiveIntegerField(default=10)),
                ('nome_orgao', models.CharField(blank=True, max_length=200)),
                ('sigla_orgao', models.CharField(blank=True, max_length=20)),
                ('divisao', models.CharField(blank=True, default='', max_length=120)),
                ('unidade', models.CharField(blank=True, default='', max_length=120)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('logradouro', models.CharField(blank=True, default='', max_length=160)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade_endereco', models.CharField(blank=True, default='', max_length=120)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sede', models.CharField(blank=True, default='', max_length=200)),
                ('nome_chefia', models.CharField(blank=True, default='', max_length=120)),
                ('cargo_chefia', models.CharField(blank=True, default='', max_length=120)),
                ('pt_ultimo_numero', models.PositiveIntegerField(default=0)),
                ('pt_ano', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='is_padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combustivel',
            name='is_padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servidor',
            name='sem_rg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servidor',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(fields=('nome',), name='cadastros_servidor_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__gt', '')), fields=('cpf',), name='cadastros_servidor_cpf_unique_nn'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('rg__gt', ''), models.Q(('rg', 'NAO POSSUI RG'), _negated=True)), fields=('rg',), name='cadastros_servidor_rg_unique_nn'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone__gt', '')), fields=('telefone',), name='cadastros_servidor_telefone_unique_nn'),
        ),
        migrations.AddField(
            model_name='assinaturaconfiguracao',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cidade_sede_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade sede padrão'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='coordenador_adm_plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='Coordenador administrativo padrão (Plano de Trabalho)'),
        ),
        migrations.AddField(
            model_name='assinaturaconfiguracao',
            name='configuracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='cadastros.configuracaosistema'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaconfiguracao',
            constraint=models.UniqueConstraint(fields=('configuracao', 'tipo', 'ordem'), name='uniq_assinatura_cfg_tipo_ordem'),
        ),
    ]
