# Generated by Django 5.2.13 on 2026-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_assinaturaconfiguracao_configuracaosistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='motoristas',
            field=models.ManyToManyField(blank=True, related_name='viaturas_que_dirige', to='cadastros.servidor', verbose_name='Motoristas'),
        ),
    ]
