# Generated by Django 5.2.13 on 2026-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_viatura_motoristas_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaconfiguracao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
