# Generated by Django 5.2.13 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_configuracaosistema_colunas_faltantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="viatura",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viaturas",
                to="cadastros.unidade",
                verbose_name="Unidade",
            ),
        ),
    ]
