# Generated by Django 5.2.13 on 2026-06-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_viatura_unidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssinaturaConfiguracao',
        ),
    ]
