# Generated by Django 5.2.13 on 2026-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_assinaturaconfiguracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_sufixo_numero',
            field=models.CharField(blank=True, default='ASCOM', help_text='Sufixo aplicado à numeração do plano (ex.: 20/2026/ASCOM).', max_length=20, verbose_name='Sufixo do número (Plano de Trabalho)'),
        ),
    ]
