# Generated by Django 5.2.13 on 2026-07-13 20:10

import re

from django.db import migrations, models

RG_NAO_POSSUI_CANONICAL = "NAO POSSUI"


def _servidor_esta_completo(servidor):
    if not (servidor.nome or "").strip():
        return False
    if not servidor.cargo_id:
        return False
    cpf = (servidor.cpf or "").strip()
    if len(cpf) != 11 or not cpf.isdigit():
        return False
    if servidor.sem_rg:
        return True
    rg = (servidor.rg or "").strip()
    return bool(rg and rg != RG_NAO_POSSUI_CANONICAL)


def _viatura_placa_valida(placa):
    p = (placa or "").strip()
    if not p or len(p) != 7:
        return False
    return bool(
        re.match(r"^[A-Z]{3}[0-9]{4}$", p) or re.match(r"^[A-Z]{3}[0-9][A-Z][0-9]{2}$", p)
    )


def _viatura_esta_completo(viatura):
    if not _viatura_placa_valida(viatura.placa):
        return False
    if not (viatura.modelo or "").strip():
        return False
    if not viatura.combustivel_id:
        return False
    return bool((viatura.tipo or "").strip())


def backfill_status(apps, schema_editor):
    Servidor = apps.get_model("cadastros", "Servidor")
    Viatura = apps.get_model("cadastros", "Viatura")

    for servidor in Servidor.objects.all():
        status = "COMPLETO" if _servidor_esta_completo(servidor) else "RASCUNHO"
        if servidor.status != status:
            Servidor.objects.filter(pk=servidor.pk).update(status=status)

    for viatura in Viatura.objects.all():
        status = "COMPLETO" if _viatura_esta_completo(viatura) else "RASCUNHO"
        if viatura.status != status:
            Viatura.objects.filter(pk=viatura.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_configuracao_divisao_unidade_fk_ramal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('COMPLETO', 'Completo')], default='RASCUNHO', max_length=20),
        ),
        migrations.AddField(
            model_name='viatura',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('COMPLETO', 'Completo')], default='RASCUNHO', max_length=20),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
