# Generated by Django 5.2.13 on 2026-07-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_servidor_viatura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='destinatario_oficio',
            field=models.ForeignKey(blank=True, help_text='A unidade lotada deste servidor vira o DESTINO do cabeçalho do Ofício.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='Destinatário padrão do Ofício'),
        ),
    ]
