# Generated by Django 5.2.16 on 2026-07-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0017_servidor_viatura_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assinaturaconfiguracao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("OFICIO", "Ofício"),
                    ("JUSTIFICATIVA", "Justificativa"),
                    ("PLANO_TRABALHO", "Plano de Trabalho"),
                    ("ORDEM_SERVICO", "Ordem de Serviço"),
                    (
                        "DESTINATARIO_OFICIO_ADJUNTO",
                        "Destinatário do Ofício – Gabinete do Delegado-Geral Adjunto",
                    ),
                    (
                        "DESTINATARIO_OFICIO_GERAL",
                        "Destinatário do Ofício – Gabinete do Delegado-Geral",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
