# Generated by Django 5.2.13 on 2026-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_configuracaosistema_destinatario_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='destinatario_oficio_cargo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='destinatario_oficio_nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='destinatario_oficio_unidade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
