# Generated by Django 5.2.13 on 2026-07-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_configuracaosistema_destinatario_oficio_cargo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_sistema', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
    ]
