# Generated by Django 5.2.13 on 2026-07-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_configuracaosistema_area'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servidor',
            name='cadastros_servidor_nome_unique',
        ),
        migrations.RemoveConstraint(
            model_name='servidor',
            name='cadastros_servidor_cpf_unique_nn',
        ),
        migrations.RemoveConstraint(
            model_name='servidor',
            name='cadastros_servidor_rg_unique_nn',
        ),
        migrations.RemoveConstraint(
            model_name='servidor',
            name='cadastros_servidor_telefone_unique_nn',
        ),
        migrations.AddField(
            model_name='servidor',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddIndex(
            model_name='servidor',
            index=models.Index(fields=['area', 'nome'], name='cadastros_srv_area_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['area', 'placa'], name='cadastros_viat_area_placa_idx'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='cadastros_servidor_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='cadastros_servidor_area_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('cpf__gt', '')), fields=('cpf',), name='cadastros_servidor_cpf_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('cpf__gt', '')), fields=('area', 'cpf'), name='cadastros_servidor_area_cpf_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('rg__gt', ''), models.Q(('rg', 'NAO POSSUI RG'), _negated=True)), fields=('rg',), name='cadastros_servidor_rg_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('rg__gt', ''), models.Q(('rg', 'NAO POSSUI RG'), _negated=True)), fields=('area', 'rg'), name='cadastros_servidor_area_rg_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('telefone__gt', '')), fields=('telefone',), name='cadastros_servidor_telefone_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('telefone__gt', '')), fields=('area', 'telefone'), name='cadastros_servidor_area_telefone_unique'),
        ),
    ]
