# Generated by Django 5.2.13 on 2026-07-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_remove_servidor_cadastros_servidor_nome_unique_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='combustivel',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combustiveis', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['area', 'nome'], name='cadastros_cargo_area_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='combustivel',
            index=models.Index(fields=['area', 'nome'], name='cadastros_comb_area_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['area', 'nome'], name='cadastros_unid_area_nome_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='cadastros_cargo_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='cadastros_cargo_area_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('is_padrao', True)), fields=('area',), name='cadastros_cargo_area_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('is_padrao', True)), fields=('is_padrao',), name='cadastros_cargo_global_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='cadastros_combustivel_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='cadastros_combustivel_area_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('is_padrao', True)), fields=('area',), name='cadastros_combustivel_area_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('is_padrao', True)), fields=('is_padrao',), name='cadastros_combustivel_global_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='cadastros_unidade_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='cadastros_unidade_area_nome_unique'),
        ),
    ]
