# Generated by Django 5.2.16 on 2026-07-28 21:11

import django.utils.timezone
from django.db import migrations, models


def semear_tabela_vigente(apps, schema_editor):
    """Semeia a tabela que estava fixada em roteiros/services/diarias.py.

    A data de início é deliberadamente anterior a qualquer roteiro do sistema:
    assim TODO roteiro já existente resolve exatamente os valores de hoje, e
    nada é recalculado. Vigências novas passam a valer da data que o operador
    escolher na tela.

    Brasília 30% entra como 140,44 e não 140,43: o valor antigo era o único dos
    nove que não seguia o arredondamento normal. Roteiros já emitidos não são
    afetados — eles carregam o valor congelado no momento da emissão.
    """
    from decimal import ROUND_HALF_UP, Decimal
    from datetime import date

    TabelaDiaria = apps.get_model("cadastros", "TabelaDiaria")
    centavos = Decimal("0.01")
    valores = {
        "INTERIOR": Decimal("290.55"),
        "CAPITAL": Decimal("371.26"),
        "BRASILIA": Decimal("468.12"),
    }
    for faixa, valor in valores.items():
        TabelaDiaria.objects.get_or_create(
            faixa=faixa,
            vigencia_inicio=date(2000, 1, 1),
            defaults={
                "valor_24h": valor,
                "valor_15": (valor * Decimal("0.15")).quantize(centavos, rounding=ROUND_HALF_UP),
                "valor_30": (valor * Decimal("0.30")).quantize(centavos, rounding=ROUND_HALF_UP),
            },
        )


def remover_tabela_vigente(apps, schema_editor):
    from datetime import date

    apps.get_model("cadastros", "TabelaDiaria").objects.filter(
        vigencia_inicio=date(2000, 1, 1)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0023_remove_configuracaosistema_divisao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faixa",
                    models.CharField(
                        choices=[
                            ("INTERIOR", "Interior"),
                            ("CAPITAL", "Capital"),
                            ("BRASILIA", "Brasília"),
                        ],
                        max_length=20,
                        verbose_name="Faixa",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(
                        help_text="Roteiros com saída a partir desta data usam estes valores.",
                        verbose_name="Vigente a partir de",
                    ),
                ),
                (
                    "valor_24h",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Diária de 24 horas",
                    ),
                ),
                (
                    "valor_15",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="15%",
                    ),
                ),
                (
                    "valor_30",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="30%",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de diárias",
                "verbose_name_plural": "Tabelas de diárias",
                "ordering": ["-vigencia_inicio", "faixa"],
                "indexes": [
                    models.Index(
                        fields=["faixa", "-vigencia_inicio"],
                        name="cadastros_tabdiaria_busca_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faixa", "vigencia_inicio"),
                        name="uniq_tabela_diaria_faixa_vigencia",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_24h__gt", 0)),
                        name="tabela_diaria_valor_24h_positivo",
                    ),
                ],
            },
        ),
            migrations.RunPython(semear_tabela_vigente, remover_tabela_vigente),
    ]
