# Generated by Django 5.2.17 on 2026-08-06 19:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0025_placa_unica_por_area"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["nome"],
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.AlterModelOptions(
            name="combustivel",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["nome"],
                "verbose_name": "Combustível",
                "verbose_name_plural": "Combustíveis",
            },
        ),
        migrations.AlterModelOptions(
            name="servidor",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["nome"],
                "verbose_name": "Servidor",
                "verbose_name_plural": "Servidores",
            },
        ),
        migrations.AlterModelOptions(
            name="unidade",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["nome"],
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
            },
        ),
        migrations.AlterModelOptions(
            name="viatura",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["placa"],
                "verbose_name": "Viatura",
                "verbose_name_plural": "Viaturas",
            },
        ),
        migrations.AlterModelManagers(
            name="cargo",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="combustivel",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="servidor",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="unidade",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="viatura",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
