# Generated by Django 5.2.17 on 2026-08-06 19:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0026_alter_cargo_options_alter_combustivel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaosistema",
            options={
                "default_manager_name": "all_objects",
                "verbose_name": "Configuração do sistema",
                "verbose_name_plural": "Configurações do sistema",
            },
        ),
        migrations.AlterModelManagers(
            name="configuracaosistema",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
