# Generated by Django 5.2.13 on 2026-06-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao/objetivo')),
                ('destino_uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF do destino')),
                ('destino_cidade', models.CharField(blank=True, default='', max_length=255, verbose_name='Cidade do destino')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horario inicial')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horario final')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preparacao', 'Em preparacao'), ('documentos_gerados', 'Documentos gerados'), ('em_execucao', 'Em execucao'), ('prestacao_pendente', 'Prestacao pendente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=30)),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID da pasta no Drive')),
                ('drive_folder_url', models.URLField(blank=True, default='', verbose_name='URL da pasta no Drive')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to='cadastros.servidor', verbose_name='Responsavel')),
                ('unidade_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='cadastros.unidade', verbose_name='Unidade responsavel')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('convite', 'Convite'), ('oficio_solicitante', 'Oficio solicitante'), ('comprovante', 'Comprovante'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('titulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Titulo')),
                ('arquivo', models.FileField(upload_to='eventos/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Anexo de evento',
                'verbose_name_plural': 'Anexos de evento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
