# Generated by Django 5.2.13 on 2026-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pcpr_comunidade', 'PCPR na Comunidade'), ('operacao_policial', 'Operação Policial'), ('parana_em_acao', 'Paraná em Ação'), ('expo', 'Expo'), ('justica_bairro', 'Justiça no Bairro'), ('outros', 'Outros')], default='', max_length=30, verbose_name='Tipo do evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titulo'),
        ),
    ]
