# Generated by Django 5.2.13 on 2026-06-18 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_tipo_motivo_titulo_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMotivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('is_padrao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modelo de motivo de evento',
                'verbose_name_plural': 'Modelos de motivo de evento',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
