# Generated by Django 5.2.13 on 2026-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_modelomotivoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_outro',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tipo personalizado (quando Outros)'),
        ),
    ]
