# Generated by Django 5.2.13 on 2026-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_tipo_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destinos_extras',
            field=models.JSONField(blank=True, default=list, verbose_name='Destinos adicionais'),
        ),
    ]
