# Generated by Django 5.2.13 on 2026-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_destinos_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preparacao', 'Em preparacao'), ('documentos_gerados', 'Documentos gerados'), ('em_execucao', 'Em execucao'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=30),
        ),
    ]
