# Generated by Django 5.2.13 on 2026-07-03 16:01

import django.utils.timezone
from django.db import migrations, models

# Codigos antigos de Evento.TIPO_CHOICES (sem "outros", tratado a parte).
_TIPOS_ANTIGOS = [
    ("pcpr_comunidade", "PCPR na Comunidade"),
    ("operacao_policial", "Operação Policial"),
    ("parana_em_acao", "Paraná em Ação"),
    ("expo", "Expo"),
    ("justica_bairro", "Justiça no Bairro"),
]


def seed_tipos_e_migrar_dados(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    TipoEvento = apps.get_model("eventos", "TipoEvento")

    tipo_por_codigo = {}
    for indice, (codigo, nome) in enumerate(_TIPOS_ANTIGOS):
        tipo_evento, _ = TipoEvento.objects.get_or_create(nome=nome, defaults={"ordem": (indice + 1) * 10})
        tipo_por_codigo[codigo] = tipo_evento

    for evento in Evento.objects.exclude(tipo="").iterator():
        if evento.tipo == "outros":
            texto = (evento.tipo_outro or "").strip()
            if not texto:
                continue
            tipo_evento, _ = TipoEvento.objects.get_or_create(nome=texto)
        else:
            tipo_evento = tipo_por_codigo.get(evento.tipo)
        if tipo_evento:
            evento.tipos.add(tipo_evento)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_eventodocumentosolicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Tipo de evento',
                'verbose_name_plural': 'Tipos de evento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.tipoevento', verbose_name='Tipos do evento'),
        ),
        migrations.RunPython(seed_tipos_e_migrar_dados, noop),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_outro',
        ),
    ]
