# Generated by Django 5.2.13 on 2026-07-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_tipoevento_remove_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='evento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento'),
        ),
    ]
