# Generated by Django 5.2.13 on 2026-07-15 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_configuracaosistema_area'),
        ('eventos', '0009_evento_cancelado_em_evento_motivo_cancelamento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['area', '-criado_em'], name='eventos_evento_area_criado_idx'),
        ),
    ]
