# Generated by Django 5.2.13 on 2026-07-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_evento_area_evento_eventos_evento_area_criado_idx'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomotivoevento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_motivo_evento', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_evento', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='modelomotivoevento',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='modelomotivoevento',
            index=models.Index(fields=['area', 'ordem', 'nome'], name='eventos_motivo_area_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoevento',
            index=models.Index(fields=['area', 'ordem', 'nome'], name='eventos_tipo_area_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='eventos_motivo_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='eventos_motivo_area_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('is_padrao', True)), fields=('area',), name='eventos_motivo_area_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('is_padrao', True)), fields=('is_padrao',), name='eventos_motivo_global_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='tipoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='eventos_tipo_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='tipoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='eventos_tipo_area_nome_unique'),
        ),
    ]
