# Generated by Django 5.2.16 on 2026-07-27 18:46

import core.uploads
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_modelomotivoevento_area_tipoevento_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoanexo',
            name='arquivo',
            field=models.FileField(upload_to='eventos/anexos/%Y/%m/', validators=[core.uploads.validate_private_document_upload], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='eventodocumentosolicitacao',
            name='arquivo',
            field=models.FileField(upload_to=eventos.models.evento_solicitacao_upload_to, validators=[core.uploads.validate_private_document_upload]),
        ),
    ]
