# Generated by Django 5.2.17 on 2026-08-06 18:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0012_alter_eventoanexo_arquivo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-data_inicio", "-criado_em"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="modelomotivoevento",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Modelo de motivo de evento",
                "verbose_name_plural": "Modelos de motivo de evento",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoevento",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Tipo de evento",
                "verbose_name_plural": "Tipos de evento",
            },
        ),
        migrations.AlterModelManagers(
            name="evento",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="modelomotivoevento",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tipoevento",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
