# Generated by Django 5.2.16 on 2026-08-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_db02_catalogos_por_area'),
        ('usuarios', '0002_novo49_catalogos_por_area'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipoevento',
            name='eventos_tipo_nome_global_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tipoevento',
            name='eventos_tipo_area_nome_unique',
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_evento', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddConstraint(
            model_name='tipoevento',
            constraint=models.UniqueConstraint(fields=('area', 'nome'), name='eventos_tipo_area_nome_unique'),
        ),
    ]
