# Generated by Django 5.2.13 on 2026-06-12 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Programa solicitante',
                'verbose_name_plural': 'Programas solicitantes',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('sufixo_numero', models.CharField(blank=True, default='', max_length=20)),
                ('data_criacao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado')], default='RASCUNHO', max_length=20)),
                ('contextualizacao', models.TextField(blank=True, default='', verbose_name='Contextualização')),
                ('programa_outros', models.CharField(blank=True, default='', max_length=200, verbose_name='Programa (outros)')),
                ('data_evento_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('horario_atendimento', models.CharField(blank=True, default='09:00 até 17:00', max_length=60, verbose_name='Horário de atendimento')),
                ('consideracao_final', models.TextField(blank=True, default='', verbose_name='Considerações finais')),
                ('coordenador_adm_modo', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('MANUAL', 'Manual')], default='SERVIDOR', max_length=10)),
                ('coordenador_adm_nome_manual', models.CharField(blank=True, default='', max_length=255)),
                ('coordenador_adm_cargo_manual', models.CharField(blank=True, default='', max_length=120)),
                ('coordenador_op_modo', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('MANUAL', 'Manual')], default='SERVIDOR', max_length=10)),
                ('coordenador_op_nome_manual', models.CharField(blank=True, default='', max_length=255)),
                ('coordenador_op_cargo_manual', models.CharField(blank=True, default='', max_length=120)),
                ('saida_sede_data', models.DateField(blank=True, null=True, verbose_name='Data de saída da sede')),
                ('saida_sede_hora', models.TimeField(blank=True, null=True, verbose_name='Hora de saída da sede')),
                ('chegada_sede_data', models.DateField(blank=True, null=True, verbose_name='Data de chegada na sede')),
                ('chegada_sede_hora', models.TimeField(blank=True, null=True, verbose_name='Hora de chegada na sede')),
                ('diarias_composicao', models.CharField(blank=True, default='', max_length=120)),
                ('diarias_valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor por servidor')),
                ('diarias_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total do plano')),
                ('metas', models.TextField(blank=True, default='')),
                ('atividades', models.TextField(blank=True, default='')),
                ('recursos_necessarios', models.TextField(blank=True, default='')),
                ('unidade_movel_texto', models.TextField(blank=True, default='')),
                ('coordenador_adm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho_coordenador_adm', to='cadastros.servidor', verbose_name='Coordenador administrativo')),
                ('coordenador_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho_coordenador_op', to='cadastros.servidor', verbose_name='Coordenador operacional')),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_trabalho', to='cadastros.cidade', verbose_name='Cidade do destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='UF do destino')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='planos_trabalho.programasolicitante', verbose_name='Programa solicitante')),
            ],
            options={
                'verbose_name': 'Plano de Trabalho',
                'verbose_name_plural': 'Planos de Trabalho',
                'ordering': ['-ano', '-numero', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EfetivoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_plano_trabalho', to='cadastros.cargo', verbose_name='Cargo')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='planos_trabalho.planotrabalho', verbose_name='Plano de trabalho')),
            ],
            options={
                'verbose_name': 'Efetivo do plano de trabalho',
                'verbose_name_plural': 'Efetivos do plano de trabalho',
                'ordering': ['plano', 'cargo__nome'],
                'constraints': [models.UniqueConstraint(fields=('plano', 'cargo'), name='planos_trabalho_efetivo_plano_cargo_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('ano', 'numero'), name='planos_trabalho_ano_numero_unique'),
        ),
    ]
