# Generated by Django 5.2.13 on 2026-06-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0005_efetivoplano_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='consideracao_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='contextualizacao_auto',
            field=models.BooleanField(default=True),
        ),
    ]
