# Generated by Django 5.2.13 on 2026-06-13 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0006_planotrabalho_consideracao_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('meta', models.TextField(verbose_name='Meta')),
                ('recurso_necessario', models.TextField(blank=True, default='', verbose_name='Recurso necessário')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Atividade (Plano de Trabalho)',
                'verbose_name_plural': 'Atividades (Plano de Trabalho)',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='atividades_selecionadas',
            field=models.ManyToManyField(blank=True, related_name='planos', to='planos_trabalho.atividadeplanotrabalho', verbose_name='Atividades previstas'),
        ),
    ]
