# Generated by Django 5.2.13 on 2026-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0009_planotrabalho_coordenacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='coordenador_adm_genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='MASCULINO', max_length=10),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='coordenador_op_genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='MASCULINO', max_length=10),
        ),
    ]
