# Generated by Django 5.2.13 on 2026-06-15 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
        ('planos_trabalho', '0010_planotrabalho_coordenador_adm_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_combinada_composicao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_combinada_valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total do plano (combinado)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_combinada_valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor por servidor (combinado)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='is_multi_evento',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('programa_outros', models.CharField(blank=True, default='', max_length=200, verbose_name='Programa (outros)')),
                ('data_evento_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('horario_atendimento', models.CharField(blank=True, default='09:00 até 17:00', max_length=60, verbose_name='Horário de atendimento')),
                ('metas', models.TextField(blank=True, default='')),
                ('atividades_texto', models.TextField(blank=True, default='')),
                ('recursos_necessarios', models.TextField(blank=True, default='')),
                ('unidade_movel_texto', models.TextField(blank=True, default='')),
                ('diarias_composicao', models.CharField(blank=True, default='', max_length=120)),
                ('diarias_valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diarias_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('atividades_selecionadas', models.ManyToManyField(blank=True, related_name='eventos', to='planos_trabalho.atividadeplanotrabalho', verbose_name='Atividades previstas')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='planos_trabalho.planotrabalho', verbose_name='Plano de trabalho')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_plano_trabalho', to='planos_trabalho.programasolicitante', verbose_name='Programa solicitante')),
            ],
            options={
                'verbose_name': 'Evento do plano de trabalho',
                'verbose_name_plural': 'Eventos do plano de trabalho',
                'ordering': ['ordem', 'data_evento_inicio', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='planodestino',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='planos_trabalho.eventoplano'),
        ),
        migrations.CreateModel(
            name='EfetivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_evento_plano_trabalho', to='cadastros.cargo', verbose_name='Cargo')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_evento_plano_trabalho', to='cadastros.unidade', verbose_name='Unidade')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='planos_trabalho.eventoplano', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Efetivo do evento',
                'verbose_name_plural': 'Efetivos do evento',
                'ordering': ['evento', 'unidade__nome', 'cargo__nome'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'unidade', 'cargo'), name='planos_trabalho_efetivo_evento_unidade_cargo_unique')],
            },
        ),
    ]
