# Generated by Django 5.2.13 on 2026-06-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
        ('planos_trabalho', '0011_planotrabalho_diarias_combinada_composicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoplano',
            name='coordenador_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_plano_coordenador_op', to='cadastros.servidor', verbose_name='Coordenador operacional'),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='coordenador_op_cargo_manual',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='coordenador_op_genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='MASCULINO', max_length=10),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='coordenador_op_modo',
            field=models.CharField(choices=[('SERVIDOR', 'Servidor'), ('MANUAL', 'Manual')], default='SERVIDOR', max_length=10),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='coordenador_op_nome_manual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='evento_em_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planos_trabalho.eventoplano'),
        ),
    ]
