# Generated by Django 5.2.13 on 2026-07-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_remove_servidor_cadastros_servidor_nome_unique_and_more'),
        ('eventos', '0010_evento_area_evento_eventos_evento_area_criado_idx'),
        ('planos_trabalho', '0015_alter_planotrabalho_evento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planotrabalho',
            name='planos_trabalho_ano_numero_unique',
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_trabalho', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddIndex(
            model_name='planotrabalho',
            index=models.Index(fields=['area', '-ano', '-numero'], name='planos_area_numero_idx'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('area__isnull', True), ('numero__isnull', False)), fields=('ano', 'numero'), name='planos_trabalho_ano_numero_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('area__isnull', False), ('numero__isnull', False)), fields=('area', 'ano', 'numero'), name='planos_trabalho_area_ano_numero_unique'),
        ),
    ]
