# Generated by Django 5.2.13 on 2026-07-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0016_remove_planotrabalho_planos_trabalho_ano_numero_unique_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeplanotrabalho',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividades_plano_trabalho', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='horarioatendimento',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_atendimento', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='programasolicitante',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_solicitantes', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='atividadeplanotrabalho',
            name='codigo',
            field=models.CharField(max_length=40, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='horarioatendimento',
            name='faixa',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='programasolicitante',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='atividadeplanotrabalho',
            index=models.Index(fields=['area', 'ordem', 'nome'], name='planos_ativ_area_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='horarioatendimento',
            index=models.Index(fields=['area', 'ordem', 'faixa'], name='planos_horario_area_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='programasolicitante',
            index=models.Index(fields=['area', 'ordem', 'nome'], name='planos_prog_area_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='atividadeplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('codigo',), name='planos_atividade_codigo_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='atividadeplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'codigo'), name='planos_atividade_area_codigo_unique'),
        ),
        migrations.AddConstraint(
            model_name='horarioatendimento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('faixa',), name='planos_horario_faixa_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='horarioatendimento',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'faixa'), name='planos_horario_area_faixa_unique'),
        ),
        migrations.AddConstraint(
            model_name='programasolicitante',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='planos_programa_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='programasolicitante',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='planos_programa_area_nome_unique'),
        ),
    ]
