# Generated by Django 5.2.13 on 2026-07-21 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0017_atividadeplanotrabalho_area_horarioatendimento_area_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetAtividadesPlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presets_atividades_plano_trabalho', to='usuarios.areatrabalho', verbose_name='Area de trabalho')),
                ('atividades', models.ManyToManyField(blank=True, related_name='presets', to='planos_trabalho.atividadeplanotrabalho', verbose_name='Atividades')),
            ],
            options={
                'verbose_name': 'Preset de atividades',
                'verbose_name_plural': 'Presets de atividades',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['area', 'ordem', 'nome'], name='planos_preset_area_ordem_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='planos_preset_nome_global_unique'), models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='planos_preset_area_nome_unique')],
            },
        ),
    ]
