# Generated by Django 5.2.13 on 2026-07-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0018_preset_atividades_plano_trabalho'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetatividadesplanotrabalho',
            name='is_padrao',
            field=models.BooleanField(default=False, verbose_name='Padrão'),
        ),
        migrations.AddConstraint(
            model_name='presetatividadesplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('is_padrao', True)), fields=('area',), name='planos_preset_area_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='presetatividadesplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('is_padrao', True)), fields=('is_padrao',), name='planos_preset_global_padrao_unique'),
        ),
    ]
