# Generated by Django 5.2.17 on 2026-08-06 20:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planos_trabalho", "0019_preset_atividades_padrao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atividadeplanotrabalho",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Atividade (Plano de Trabalho)",
                "verbose_name_plural": "Atividades (Plano de Trabalho)",
            },
        ),
        migrations.AlterModelOptions(
            name="horarioatendimento",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "faixa"],
                "verbose_name": "Horário de atendimento",
                "verbose_name_plural": "Horários de atendimento",
            },
        ),
        migrations.AlterModelOptions(
            name="planotrabalho",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-ano", "-numero", "-created_at"],
                "verbose_name": "Plano de Trabalho",
                "verbose_name_plural": "Planos de Trabalho",
            },
        ),
        migrations.AlterModelOptions(
            name="presetatividadesplanotrabalho",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Preset de atividades",
                "verbose_name_plural": "Presets de atividades",
            },
        ),
        migrations.AlterModelOptions(
            name="programasolicitante",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Programa solicitante",
                "verbose_name_plural": "Programas solicitantes",
            },
        ),
        migrations.AlterModelManagers(
            name="atividadeplanotrabalho",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="horarioatendimento",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="planotrabalho",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="presetatividadesplanotrabalho",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="programasolicitante",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
