"""`DB-08`: posição duplicada nas coleções ordenadas do plano de trabalho.

São **três** constraints, e duas delas cobrem um único modelo por um motivo que a
forma ingênua erra: `PlanoDestino.evento` é anulável, e em SQL NULL é distinto de
NULL num índice único. Uma constraint só sobre `(plano, evento, ordem)` deixaria
sem proteção justamente o caso mais comum — os destinos de rascunho, que têm
`evento IS NULL`. Daí o par parcial.

E o invariante **não** é `(plano, ordem)`: um plano guarda ao mesmo tempo o
rascunho e as cópias por evento, e `services.py:968` copia `d.ordem` tal e qual ao
comitar o evento — `(plano, ordem)` reprovaria produção no primeiro commit.

Todas simples, não adiadas: os escritores apagam antes de recriar
(`forms.py:459`, `services.py:964`, `services.py:1030`) e `EventoPlano` só
acrescenta ao fim (`services.py:943`).

**Limite 4 do `AGENTS.md` — rode antes do deploy:**

```sql
SELECT plano_id, ordem, COUNT(*) FROM planos_trabalho_planodestino
 WHERE evento_id IS NULL GROUP BY plano_id, ordem HAVING COUNT(*) > 1;

SELECT evento_id, ordem, COUNT(*) FROM planos_trabalho_planodestino
 WHERE evento_id IS NOT NULL GROUP BY evento_id, ordem HAVING COUNT(*) > 1;

SELECT plano_id, ordem, COUNT(*) FROM planos_trabalho_eventoplano
 GROUP BY plano_id, ordem HAVING COUNT(*) > 1;
```

Medido em 07/08/2026 no banco de desenvolvimento: 0 grupos nas três.
"""
# Generated by Django 5.2.17 on 2026-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0028_tabela_diaria_derivados_positivos"),
        ("planos_trabalho", "0021_plano_periodo_e_diarias"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventoplano",
            constraint=models.UniqueConstraint(
                fields=("plano", "ordem"), name="evento_plano_ordem_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="planodestino",
            constraint=models.UniqueConstraint(
                condition=models.Q(("evento__isnull", True)),
                fields=("plano", "ordem"),
                name="plano_destino_rascunho_ordem_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="planodestino",
            constraint=models.UniqueConstraint(
                condition=models.Q(("evento__isnull", False)),
                fields=("evento", "ordem"),
                name="plano_destino_evento_ordem_unique",
            ),
        ),
    ]
