# Generated by Django 5.2.16 on 2026-08-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_trabalho', '0024_db02_catalogos_por_area'),
        ('usuarios', '0002_novo49_catalogos_por_area'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atividadeplanotrabalho',
            name='planos_atividade_codigo_global_unique',
        ),
        migrations.RemoveConstraint(
            model_name='atividadeplanotrabalho',
            name='planos_atividade_area_codigo_unique',
        ),
        migrations.RemoveConstraint(
            model_name='horarioatendimento',
            name='planos_horario_faixa_global_unique',
        ),
        migrations.RemoveConstraint(
            model_name='horarioatendimento',
            name='planos_horario_area_faixa_unique',
        ),
        migrations.RemoveConstraint(
            model_name='programasolicitante',
            name='planos_programa_nome_global_unique',
        ),
        migrations.RemoveConstraint(
            model_name='programasolicitante',
            name='planos_programa_area_nome_unique',
        ),
        migrations.AlterField(
            model_name='atividadeplanotrabalho',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_plano_trabalho', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='horarioatendimento',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_atendimento', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='programasolicitante',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_solicitantes', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddConstraint(
            model_name='atividadeplanotrabalho',
            constraint=models.UniqueConstraint(fields=('area', 'codigo'), name='planos_atividade_area_codigo_unique'),
        ),
        migrations.AddConstraint(
            model_name='horarioatendimento',
            constraint=models.UniqueConstraint(fields=('area', 'faixa'), name='planos_horario_area_faixa_unique'),
        ),
        migrations.AddConstraint(
            model_name='programasolicitante',
            constraint=models.UniqueConstraint(fields=('area', 'nome'), name='planos_programa_area_nome_unique'),
        ),
    ]
