# Generated by Django 5.2.13 on 2026-06-18 01:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('periodo', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preenchimento', 'Em preenchimento'), ('finalizado', 'Finalizado')], default='rascunho', max_length=30)),
                ('assinatura_status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('dispensado', 'Dispensado')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Diário de bordo',
                'verbose_name_plural': 'Diários de bordo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DiarioBordoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('hora_chegada', models.TimeField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, default='', max_length=255)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('atividades', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='prestacoes.diariobordo')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diario_bordo_registros_motorista', to='cadastros.servidor')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diario_bordo_registros', to='cadastros.viatura')),
            ],
            options={
                'verbose_name': 'Registro do diário de bordo',
                'verbose_name_plural': 'Registros do diário de bordo',
                'ordering': ['data', 'hora_saida', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('periodo', models.CharField(blank=True, default='', max_length=120)),
                ('local', models.CharField(blank=True, default='', max_length=255)),
                ('servidores_participantes', models.TextField(blank=True, default='')),
                ('atividades_realizadas', models.TextField(blank=True, default='')),
                ('resultados_obtidos', models.TextField(blank=True, default='')),
                ('intercorrencias', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preenchimento', 'Em preenchimento'), ('finalizado', 'Finalizado')], default='rascunho', max_length=30)),
                ('assinatura_status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('dispensado', 'Dispensado')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_tecnicos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Relatório técnico',
                'verbose_name_plural': 'Relatórios técnicos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preenchimento', 'Em preenchimento'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('finalizada', 'Finalizada')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('assinatura_responsavel_status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('dispensado', 'Dispensado')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('diario_bordo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_contas', to='prestacoes.diariobordo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_contas', to='eventos.evento')),
                ('relatorio_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_contas', to='prestacoes.relatoriotecnico')),
            ],
            options={
                'verbose_name': 'Prestação de contas',
                'verbose_name_plural': 'Prestações de contas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
