# Generated by Django 5.2.17 on 2026-08-06 20:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AlterModelManagers(
            name="auditevent",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
