# Generated by Django 5.2.13 on 2026-05-10 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('oficios', '0005_oficio_motorista_oficio_protocolo_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoArtefato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_index=True, max_length=64)),
                ('formato', models.CharField(db_index=True, max_length=16)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('hash_sha256_assinado', models.CharField(blank=True, default='', max_length=64)),
                ('arquivo', models.FileField(upload_to='documentos/gerados/%Y/%m/')),
                ('arquivo_assinado', models.FileField(blank=True, upload_to='documentos/assinados/%Y/%m/')),
                ('assinatura_backend', models.CharField(blank=True, default='', max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='oficios.oficio')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Artefato documental',
                'verbose_name_plural': 'Artefatos documentais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
