# Generated by Django 5.2.13 on 2026-06-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentoartefato_cache_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoartefato',
            name='arquivo_assinado',
        ),
        migrations.RemoveField(
            model_name='documentoartefato',
            name='assinado_em',
        ),
        migrations.RemoveField(
            model_name='documentoartefato',
            name='assinatura_backend',
        ),
        migrations.RemoveField(
            model_name='documentoartefato',
            name='hash_sha256_assinado',
        ),
    ]
