# Generated by Django 5.2.15 on 2026-06-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_drop_assinaturas_tables"),
        ("eventos", "0007_eventodocumentosolicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoartefato",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                help_text="Evento de origem (usado por documentos que se ligam ao evento, ex.: plano de trabalho).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_gerados",
                to="eventos.evento",
            ),
        ),
        migrations.AddField(
            model_name="documentoartefato",
            name="nome_drive",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome 'bonito' do arquivo no Drive, calculado na geração.",
                max_length=255,
            ),
        ),
    ]
