# Generated by Django 5.2.13 on 2026-07-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documentoartefato_evento_and_more'),
        ('eventos', '0009_evento_cancelado_em_evento_motivo_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoartefato',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento de origem (usado por documentos que se ligam ao evento, ex.: plano de trabalho).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='eventos.evento'),
        ),
    ]
