# Generated by Django 5.2.13 on 2026-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documentoartefato_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='arquivo_assinado',
            field=models.FileField(blank=True, help_text='Versão assinada anexada manualmente (substitui a gerada na exibição/download/Drive).', upload_to='documentos/assinados/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='documentoartefato',
            name='assinado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoartefato',
            name='assinado_nome_original',
            field=models.CharField(blank=True, default='', help_text='Nome do arquivo enviado pelo usuário, para exibição.', max_length=255),
        ),
    ]
