# Generated by Django 5.2.13 on 2026-07-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_adiciona_arquivo_assinado'),
        ('termos', '0005_alter_termoautorizacao_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='termo',
            field=models.ForeignKey(blank=True, help_text='Termo de autorização avulso de origem (cadastro em `termos`, pode não ter ofício).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_gerados', to='termos.termoautorizacao'),
        ),
    ]
