# Generated by Django 5.2.13 on 2026-07-15 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_adiciona_termo_fk'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_artefatos', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
    ]
