# Generated by Django 5.2.16 on 2026-07-27 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_documentoartefato_area'),
        ('eventos', '0012_alter_eventoanexo_arquivo_and_more'),
        ('oficios', '0017_configuracaonumeracaooficio'),
        ('termos', '0006_termoautorizacao_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoartefato',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento de origem (usado por documentos que se ligam ao evento, ex.: plano de trabalho).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='documentoartefato',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='oficios.oficio'),
        ),
        migrations.AlterField(
            model_name='documentoartefato',
            name='termo',
            field=models.ForeignKey(blank=True, help_text='Termo de autorização avulso de origem (cadastro em `termos`, pode não ter ofício).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='termos.termoautorizacao'),
        ),
        migrations.CreateModel(
            name='DocumentoAssinaturaVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='documentos/assinados/versoes/%Y/%m/')),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_assinadas', to='documentos.documentoartefato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão assinada',
                'verbose_name_plural': 'Versões assinadas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
