# Generated by Django 5.2.17 on 2026-08-06 18:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0011_documentogeracao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentoartefato",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-criado_em"],
                "verbose_name": "Artefato documental",
                "verbose_name_plural": "Artefatos documentais",
            },
        ),
        migrations.AlterModelOptions(
            name="documentogeracao",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-criado_em"],
                "verbose_name": "Geração documental",
                "verbose_name_plural": "Gerações documentais",
            },
        ),
        migrations.AlterModelManagers(
            name="documentoartefato",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="documentogeracao",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
