# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("termos", "0002_termoautorizacao_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="termoautorizacao",
            name="destinos_extras",
            field=models.JSONField(blank=True, default=list, verbose_name="Destinos adicionais"),
        ),
    ]
