# Generated by Django 5.2.13 on 2026-07-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0005_alter_termoautorizacao_evento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoautorizacao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos_autorizacao', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
    ]
