# Generated by Django 5.2.16 on 2026-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0024_tabeladiaria"),
        ("eventos", "0012_alter_eventoanexo_arquivo_and_more"),
        ("oficios", "0017_configuracaonumeracaooficio"),
        ("termos", "0006_termoautorizacao_area"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="termoautorizacao",
            index=models.Index(
                fields=["area", "-created_at"], name="termo_area_created_idx"
            ),
        ),
    ]
