# Generated by Django 5.2.17 on 2026-08-06 15:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("termos", "0007_p03_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termoautorizacao",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "Termo de autorizacao",
                "verbose_name_plural": "Termos de autorizacao",
            },
        ),
        migrations.AlterModelManagers(
            name="termoautorizacao",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
