# Generated by Django 5.2.13 on 2026-05-10 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficios', '0005_oficio_motorista_oficio_protocolo_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('is_padrao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modelo de justificativa',
                'verbose_name_plural': 'Modelos de justificativa',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(blank=True, default='')),
                ('obrigatoria', models.BooleanField(default=False)),
                ('dias_antecedencia', models.IntegerField(blank=True, null=True)),
                ('prazo_dias', models.PositiveIntegerField(default=10)),
                ('primeira_saida_dt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada')], default='RASCUNHO', max_length=20)),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa', to='oficios.oficio')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='justificativas.modelojustificativa')),
            ],
            options={
                'verbose_name': 'Justificativa de ofício',
                'verbose_name_plural': 'Justificativas de ofício',
            },
        ),
    ]
