# Generated by Django 5.2.17 on 2026-08-06 20:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("justificativas", "0004_modelojustificativa_area_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelojustificativa",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Modelo de justificativa",
                "verbose_name_plural": "Modelos de justificativa",
            },
        ),
        migrations.AlterModelManagers(
            name="modelojustificativa",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
