# Generated by Django 5.2.13 on 2026-06-17 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, default='', help_text='Número no eProtocolo (ex.: 24.123.456-7). Vazio enquanto pendente.', max_length=30, verbose_name='Número do protocolo')),
                ('status_local', models.CharField(choices=[('rascunho', 'Rascunho'), ('criado', 'Criado'), ('documentos_enviados', 'Documentos enviados'), ('aguardando_assinatura', 'Aguardando assinatura'), ('em_tramitacao', 'Em tramitação'), ('com_pendencia', 'Com pendência'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=30)),
                ('situacao_eprotocolo', models.CharField(blank=True, default='', max_length=60, verbose_name='Situação no eProtocolo')),
                ('origem_tipo', models.CharField(choices=[('interna', 'Documento interno'), ('manual', 'Externo / manual')], default='interna', max_length=10)),
                ('origem_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('assunto_resumo', models.CharField(blank=True, default='', max_length=255)),
                ('descricao_resumo', models.TextField(blank=True, default='')),
                ('cod_orgao', models.CharField(blank=True, default='', max_length=30)),
                ('nome_orgao', models.CharField(blank=True, default='', max_length=200)),
                ('cod_local_origem', models.CharField(blank=True, default='', max_length=30)),
                ('nome_local_origem', models.CharField(blank=True, default='', max_length=200)),
                ('cod_local_atual', models.CharField(blank=True, default='', max_length=30)),
                ('nome_local_atual', models.CharField(blank=True, default='', max_length=200)),
                ('cpf_responsavel_atual', models.CharField(blank=True, default='', max_length=11)),
                ('nome_responsavel_atual', models.CharField(blank=True, default='', max_length=200)),
                ('criado_no_sistema_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('criado_no_eprotocolo_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_movimentacao_em', models.DateTimeField(blank=True, null=True)),
                ('payload_atual_json', models.JSONField(blank=True, default=dict)),
                ('modo_mock', models.BooleanField(default=False, help_text='Criado/atualizado em modo mock (sem integração real).')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('origem_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-criado_no_sistema_em'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Ofício'), ('TERMO_AUTORIZACAO', 'Termo de Autorização'), ('JUSTIFICATIVA', 'Justificativa'), ('PLANO_TRABALHO', 'Plano de Trabalho'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('ANEXO', 'Anexo manual')], default='ANEXO', max_length=30)),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=255)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='protocolos/documentos/')),
                ('codigo_documento_eprotocolo', models.CharField(blank=True, default='', max_length=60)),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('esta_no_volume', models.BooleanField(default=False)),
                ('assinado', models.BooleanField(default=False)),
                ('origem_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('origem_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Documento do protocolo',
                'verbose_name_plural': 'Documentos do protocolo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_assinante', models.CharField(blank=True, default='', max_length=11)),
                ('nome_assinante', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('cancelado', 'Cancelado'), ('erro', 'Erro'), ('desconhecido', 'Desconhecido')], default='pendente', max_length=20)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('solicitado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='protocolos.protocolo')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='protocolos.protocolodocumento')),
            ],
            options={
                'verbose_name': 'Assinatura do protocolo',
                'verbose_name_plural': 'Assinaturas do protocolo',
                'ordering': ['-solicitado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=80)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('metodo', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('modo_mock', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Log de integração',
                'verbose_name_plural': 'Logs de integração',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=60)),
                ('descricao', models.TextField(blank=True, default='')),
                ('local', models.CharField(blank=True, default='', max_length=200)),
                ('usuario', models.CharField(blank=True, default='', max_length=200)),
                ('data_movimentacao', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Movimentação do protocolo',
                'verbose_name_plural': 'Movimentações do protocolo',
                'ordering': ['-data_movimentacao', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pendencia', models.CharField(blank=True, default='', max_length=60)),
                ('tipo', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('cpf_destinatario', models.CharField(blank=True, default='', max_length=11)),
                ('nome_destinatario', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias', to='protocolos.protocolodocumento')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Pendência do protocolo',
                'verbose_name_plural': 'Pendências do protocolo',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_local_de', models.CharField(blank=True, default='', max_length=30)),
                ('nome_local_de', models.CharField(blank=True, default='', max_length=200)),
                ('cod_local_para', models.CharField(blank=True, default='', max_length=30)),
                ('nome_local_para', models.CharField(blank=True, default='', max_length=200)),
                ('cpf_destinatario', models.CharField(blank=True, default='', max_length=11)),
                ('nome_destinatario', models.CharField(blank=True, default='', max_length=200)),
                ('parecer', models.TextField(blank=True, default='')),
                ('data_tramitacao', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Tramitação do protocolo',
                'verbose_name_plural': 'Tramitações do protocolo',
                'ordering': ['-data_tramitacao', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='protocolo',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='protocolo_numero_unico_quando_preenchido'),
        ),
    ]
