# Generated by Django 5.2.13 on 2026-06-11 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0013_remove_assinatura_fields'),
        ('oficios', '0007_oficio_servidores_termo_autorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data_evento_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('destinos', models.ManyToManyField(blank=True, related_name='ordens_servico', to='cadastros.cidade', verbose_name='Destinos')),
                ('oficios', models.ManyToManyField(blank=True, related_name='ordens_servico', to='oficios.oficio', verbose_name='Ofícios vinculados')),
                ('servidores', models.ManyToManyField(blank=True, related_name='ordens_servico', to='cadastros.servidor', verbose_name='Servidores')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-ano', '-numero'],
            },
        ),
    ]
