# Generated by Django 5.2.13 on 2026-07-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_ordemservico_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento'),
        ),
    ]
