# Generated by Django 5.2.17 on 2026-08-06 15:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordens_servico", "0009_ordemservico_numero_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordemservico",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-ano", "-numero"],
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.AlterModelManagers(
            name="ordemservico",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
