# Generated by Django 5.2.13 on 2026-07-15 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(max_length=30, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area de trabalho',
                'verbose_name_plural': 'Areas de trabalho',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('LEITOR', 'Leitor')], default='EDITOR', max_length=20)),
                ('area_padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuario', to='usuarios.areatrabalho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo usuario-area',
                'verbose_name_plural': 'Vinculos usuario-area',
                'ordering': ['usuario__username', 'area__sigla'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'area'), name='usuarios_vinculo_usuario_area_unique'), models.UniqueConstraint(condition=models.Q(('area_padrao', True), ('ativo', True)), fields=('usuario',), name='usuarios_vinculo_usuario_area_padrao_unica')],
            },
        ),
    ]
