# Generated by Django 5.2.13 on 2026-05-11 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_documentoartefato_cache_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoChaveAssinatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('storage_kind', models.CharField(choices=[('pkcs12', 'PKCS#12'), ('pkcs11', 'PKCS#11')], default='pkcs12', max_length=16)),
                ('alias', models.CharField(blank=True, default='', max_length=120)),
                ('pkcs12_path', models.CharField(blank=True, default='', max_length=512)),
                ('certificate_fingerprint_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('ativo', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Configuração de chave de assinatura',
                'verbose_name_plural': 'Configurações de chaves de assinatura',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('valid', 'Válida'), ('invalid', 'Inválida'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16)),
                ('signer_subject', models.CharField(blank=True, default='', max_length=512)),
                ('signer_serial', models.CharField(blank=True, default='', max_length=255)),
                ('hash_documento', models.CharField(max_length=64)),
                ('hash_documento_assinado', models.CharField(blank=True, default='', max_length=64)),
                ('signature_field_name', models.CharField(default='AssinaturaCentralViagens', max_length=120)),
                ('appearance', models.JSONField(blank=True, default=dict)),
                ('evidencias', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_registro', to='documentos.documentoartefato')),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_emitidas', to='assinaturas.configuracaochaveassinatura')),
            ],
            options={
                'verbose_name': 'Assinatura digital',
                'verbose_name_plural': 'Assinaturas digitais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoAssinatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='assinaturas.assinaturadigital')),
            ],
            options={
                'verbose_name': 'Evento de assinatura',
                'verbose_name_plural': 'Eventos de assinatura',
                'ordering': ['-criado_em'],
            },
        ),
    ]
