# Generated by Django 5.2.13 on 2026-05-12 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_add_assinatura_etiqueta_campos'),
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('documentos', '0002_documentoartefato_cache_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAssinaturaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('nome_assinante_snapshot', models.CharField(max_length=160)),
                ('cpf_assinante_snapshot', models.CharField(blank=True, default='', max_length=14)),
                ('email_assinante_snapshot', models.EmailField(blank=True, default='', max_length=254)),
                ('cargo_assinante_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('unidade_assinante_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('tipo_documento', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('substituido', 'Substituido')], db_index=True, default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('posicao_etiqueta_json', models.JSONField(blank=True, default=dict)),
                ('hash_documento_original', models.CharField(blank=True, default='', max_length=64)),
                ('hash_documento_assinado', models.CharField(blank=True, default='', max_length=64)),
                ('auditoria', models.JSONField(blank=True, default=dict)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_assinatura', to='documentos.documentoartefato')),
                ('assinante_servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_assinatura_documental', to='cadastros.servidor')),
                ('assinante_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_assinatura_documental', to=settings.AUTH_USER_MODEL)),
                ('assinatura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_documental', to='assinaturas.assinaturadigital')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_assinatura_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de assinatura documental',
                'verbose_name_plural': 'Pedidos de assinatura documental',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['artefato', 'status', 'expira_em'], name='assinaturas_artefat_6f5c37_idx')],
            },
        ),
    ]
