# Generated by Django 5.2.13 on 2026-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_pedidoassinaturadocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='ip_visualizacao',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='motivo_recusa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='recusado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='revogado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='user_agent_visualizacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidoassinaturadocumento',
            name='visualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoassinaturadocumento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('visualizada', 'Visualizada'), ('assinado', 'Assinado'), ('expirado', 'Expirado'), ('recusada', 'Recusada'), ('revogada', 'Revogada'), ('cancelado', 'Cancelado'), ('substituido', 'Substituido')], db_index=True, default='pendente', max_length=20),
        ),
    ]
