# Generated by Django 5.2.13 on 2026-05-04 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_cidade_estado_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteiros_como_destino', to='cadastros.cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteiros_como_origem', to='cadastros.cidade')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-updated_at', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TrechoRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trechos_como_destino', to='cadastros.cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trechos_como_origem', to='cadastros.cidade')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='roteiros.roteiro')),
            ],
            options={
                'verbose_name': 'Trecho de roteiro',
                'verbose_name_plural': 'Trechos de roteiro',
                'ordering': ['roteiro', 'ordem'],
            },
        ),
    ]
