# Generated by Django 5.2.13 on 2026-05-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('roteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roteiro',
            options={'ordering': ['-created_at'], 'verbose_name': 'Roteiro', 'verbose_name_plural': 'Roteiros'},
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='origem',
        ),
        migrations.AddField(
            model_name='roteiro',
            name='chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora chegada'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade sede'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.estado', verbose_name='Estado sede'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='quantidade_diarias',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Quantidade de diárias'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno - chegada'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno - duração (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno - saída'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora saída'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='tipo',
            field=models.CharField(choices=[('EVENTO', 'Vinculado a evento'), ('AVULSO', 'Avulso')], default='AVULSO', max_length=20, verbose_name='Tipo de roteiro'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='valor_diarias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor das diárias'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='valor_diarias_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Valor das diárias por extenso'),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='RoteiroDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteiro_destinos', to='cadastros.cidade', verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteiro_destinos', to='cadastros.estado', verbose_name='Estado')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='roteiros.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Destino do roteiro',
                'verbose_name_plural': 'Destinos do roteiro',
                'ordering': ['roteiro', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RoteiroTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('IDA', 'Ida'), ('RETORNO', 'Retorno')], default='IDA', max_length=10, verbose_name='Tipo')),
                ('saida_dt', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('chegada_dt', models.DateTimeField(blank=True, null=True, verbose_name='Chegada')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância (km)')),
                ('duracao_estimada_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)')),
                ('tempo_cru_estimado_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo cru estimado (min)')),
                ('tempo_adicional_min', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo adicional (min)')),
                ('rota_fonte', models.CharField(blank=True, default='', max_length=30, verbose_name='Fonte da rota')),
                ('rota_calculada_em', models.DateTimeField(blank=True, null=True, verbose_name='Rota calculada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.cidade', verbose_name='Cidade destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='Estado destino')),
                ('origem_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.cidade', verbose_name='Cidade origem')),
                ('origem_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='Estado origem')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='roteiros.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Trecho do roteiro',
                'verbose_name_plural': 'Trechos do roteiro',
                'ordering': ['roteiro', 'ordem'],
            },
        ),
        migrations.DeleteModel(
            name='TrechoRoteiro',
        ),
    ]
