# Generated by Django 5.2.13 on 2026-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0002_legacy_roteiro_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='rota_ajuste_justificativa',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa do ajuste manual da rota'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_assinatura',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Assinatura para cache da rota'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota consolidada calculada em'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_distancia_calculada_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância calculada (km)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_distancia_manual_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância ajustada manualmente (km)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_duracao_calculada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração calculada (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_duracao_manual_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração ajustada manualmente (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Fonte do cálculo da rota'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Geometria da rota (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('calculada', 'Calculada'), ('manual', 'Manual'), ('erro', 'Erro'), ('desatualizada', 'Desatualizada')], default='pendente', max_length=20, verbose_name='Status da rota no mapa'),
        ),
    ]
