# Generated by Django 5.2.13 on 2026-07-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_cancelado_em_evento_motivo_cancelamento'),
        ('roteiros', '0005_roteiro_cancelado_roteiro_cancelado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiro',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to='eventos.evento'),
        ),
    ]
