# Generated by Django 5.2.16 on 2026-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0024_tabeladiaria"),
        ("roteiros", "0007_roteiro_area"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="roteirodestino",
            index=models.Index(
                fields=["roteiro", "ordem"], name="roteiro_destino_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roteirotrecho",
            index=models.Index(
                fields=["roteiro", "ordem"], name="roteiro_trecho_ordem_idx"
            ),
        ),
    ]
