# Generated by Django 5.2.17 on 2026-08-06 18:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roteiros", "0008_p03_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roteiro",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "Roteiro",
                "verbose_name_plural": "Roteiros",
            },
        ),
        migrations.AlterModelManagers(
            name="roteiro",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
