"""`DB-08`: dois destinos na mesma posição do mesmo roteiro.

Destino duplicado é contado **duas vezes pelo motor de diárias** e sai duas vezes
no ofício e no termo. Constraint simples, não adiada: o único escritor
(`roteiro_logic._salvar_roteiro_avulso_from_roteiro_state`) apaga todos os destinos antes de recriar com
`enumerate`, então não existe reordenação por troca de posição neste caminho.

**Limite 4 do `AGENTS.md` — rode antes do deploy:**

```sql
SELECT roteiro_id, ordem, COUNT(*)
  FROM roteiros_roteirodestino
 GROUP BY roteiro_id, ordem HAVING COUNT(*) > 1;
```

Medido em 07/08/2026 no banco de desenvolvimento: 0 grupos em 60 linhas.
"""
# Generated by Django 5.2.17 on 2026-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0028_tabela_diaria_derivados_positivos"),
        ("roteiros", "0011_roteiro_roteiro_ida_ordenada"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roteirodestino",
            constraint=models.UniqueConstraint(
                fields=("roteiro", "ordem"), name="roteiro_destino_ordem_unique"
            ),
        ),
    ]
