#!/usr/bin/env python3
"""Gera bundles de entrega do shell (NOVO-12).

Concatena CSS/JS do shell na ordem canônica — a mesma que `templates/base.html`
usava antes do bundle — sem alterar as fontes. Os arquivos de origem continuam
sendo a unidade de edição; os bundles existem só para cortar o waterfall HTTP.

Uso:
  python scripts/build_shell_bundles.py          # gera
  python scripts/build_shell_bundles.py --check  # falha se desatualizado
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "static"

# Ordem = cascata histórica de templates/base.html (antes do NOVO-12).
# theme-shared.js / theme-init.js ficam fora do bundle JS (head, sem defer).
SHELL_CSS: tuple[str, ...] = (
    "css/style.css",
    "css/base/03-theme-dark.css",
    "css/base/utilities.css",
    "css/layout/page-shell.css",
    "css/actions/buttons.css",
    "css/fields/field.css",
    "css/fields/date-picker.css",
    "css/fields/file-picker.css",
    "css/actions/action-system.css",
    "css/lists/record-list.css",
    "css/lists/list-tabs.css",
    "css/lists/filter-header.css",
    "css/fields/form-panel.css",
    "css/fields/form-sections.css",
    "css/feedback/pendencias.css",
    "css/feedback/summary-items.css",
    "css/feedback/notice.css",
    "css/feedback/metric.css",
    "css/layout/app-shell.css",
    "css/lists/content-cards.css",
    "css/pages/document-viewer.css",
    "css/feedback/dialog.css",
    "css/feedback/document-download-loading.css",
    "css/components/theme-dark-components.css",
    "css/lists/list-header.css",
)

SHELL_JS: tuple[str, ...] = (
    "js/theme-toggle.js",
    "js/core/http.js",
    "js/core/app.js",
    "js/autosave.js",
    "js/components/sidebar.js",
    "js/components/masks.js",
    "js/components/state-toggle.js",
    "js/components/card-toggle.js",
    "js/components/collection.js",
    "js/components/segment-nav.js",
    "js/components/icon-tooltips.js",
    "js/components/overlay.js",
    "js/components/attach-signed-modal.js",
    "js/components/file-picker.js",
    "js/components/signature-actions.js",
    "js/components/picker.js",
    "js/components/picker-select.js",
    "js/components/location-rows.js",
    "js/components/document-source.js",
    "js/components/document-search.js",
    "js/components/date-picker.js",
    "js/components/fields-init.js",
    "js/components/document-download.js",
    "js/components/extra-download.js",
    "js/components/wizard-sticky-header.js",
)

CSS_BUNDLE = STATIC / "css" / "shell.bundle.css"
JS_BUNDLE = STATIC / "js" / "shell.bundle.js"

BANNER = (
    "/* AUTO-GENERATED by scripts/build_shell_bundles.py — do not edit. "
    "Edit the source files listed below and re-run the script. */\n"
)


def _read(rel: str) -> str:
    path = STATIC / rel
    if not path.is_file():
        raise FileNotFoundError(f"fonte ausente: {rel}")
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def _concat(sources: tuple[str, ...], kind: str) -> str:
    parts: list[str] = [BANNER, f"/* shell {kind} sources ({len(sources)}): */\n"]
    for rel in sources:
        parts.append(f"\n/* >>> {rel} >>> */\n")
        parts.append(_read(rel))
        if not parts[-1].endswith("\n"):
            parts.append("\n")
        parts.append(f"/* <<< {rel} <<< */\n")
    return "".join(parts)


def build() -> tuple[str, str]:
    css = _concat(SHELL_CSS, "css")
    js = _concat(SHELL_JS, "js")
    CSS_BUNDLE.parent.mkdir(parents=True, exist_ok=True)
    JS_BUNDLE.parent.mkdir(parents=True, exist_ok=True)
    CSS_BUNDLE.write_text(css, encoding="utf-8", newline="\n")
    JS_BUNDLE.write_text(js, encoding="utf-8", newline="\n")
    return css, js


def check() -> int:
    expected_css = _concat(SHELL_CSS, "css")
    expected_js = _concat(SHELL_JS, "js")
    errors: list[str] = []
    if not CSS_BUNDLE.is_file():
        errors.append(f"ausente: {CSS_BUNDLE.relative_to(ROOT).as_posix()}")
    elif CSS_BUNDLE.read_text(encoding="utf-8") != expected_css:
        errors.append(
            f"desatualizado: {CSS_BUNDLE.relative_to(ROOT).as_posix()} "
            "(rode python scripts/build_shell_bundles.py)"
        )
    if not JS_BUNDLE.is_file():
        errors.append(f"ausente: {JS_BUNDLE.relative_to(ROOT).as_posix()}")
    elif JS_BUNDLE.read_text(encoding="utf-8") != expected_js:
        errors.append(
            f"desatualizado: {JS_BUNDLE.relative_to(ROOT).as_posix()} "
            "(rode python scripts/build_shell_bundles.py)"
        )
    if errors:
        print("NOVO-12 shell bundles:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1
    print(
        f"OK: shell bundles atualizados "
        f"({len(SHELL_CSS)} css, {len(SHELL_JS)} js)"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="não escreve; exit 1 se bundles ausentes ou desatualizados",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check()
    css, js = build()
    print(
        f"gerado {CSS_BUNDLE.relative_to(ROOT).as_posix()} "
        f"({len(css)} bytes) e {JS_BUNDLE.relative_to(ROOT).as_posix()} "
        f"({len(js)} bytes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
