# Generated by Django 5.2.13 on 2026-06-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
        ('oficios', '0008_oficio_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preenchimento', 'Em preenchimento'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=30)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_contas', to='oficios.oficio')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_contas', to='cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Prestação de Contas',
                'verbose_name_plural': 'Prestações de Contas',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('oficio', 'servidor'), name='unique_prestacao_por_servidor_oficio')],
            },
        ),
    ]
