# Generated by Django 5.2.13 on 2026-06-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaria', models.CharField(blank=True, default='', max_length=255)),
                ('translado', models.CharField(blank=True, default='', max_length=255)),
                ('passagem', models.CharField(blank=True, default='', max_length=255)),
                ('atividade', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('medidas', models.TextField(blank=True, default='')),
                ('info_complementares', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_tecnico', to='prestacoes_contas.prestacaocontas')),
            ],
            options={
                'verbose_name': 'Relatório Técnico',
                'verbose_name_plural': 'Relatórios Técnicos',
            },
        ),
    ]
