# Generated by Django 5.2.13 on 2026-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0002_relatoriotecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnico',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
