# Generated by Django 5.2.13 on 2026-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0003_relatoriotecnico_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTextoRelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('motivo', 'Descrição do evento'), ('atividade', 'Objetivo da participação'), ('conclusao', 'Conclusão'), ('medidas', 'Medidas a serem adotadas pelo órgão'), ('info_complementares', 'Informações complementares')], db_index=True, max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Modelo de texto do RT',
                'verbose_name_plural': 'Modelos de texto do RT',
                'ordering': ['campo', 'ordem', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('campo', 'nome'), name='unique_modelo_texto_rt_campo_nome')],
            },
        ),
    ]
