# Generated by Django 5.2.13 on 2026-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0004_modelotextorelatoriotecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelotextorelatoriotecnico',
            name='campo',
            field=models.CharField(choices=[('atividade', 'Objetivo da participação'), ('conclusao', 'Conclusão'), ('medidas', 'Medidas a serem adotadas pelo órgão'), ('info_complementares', 'Informações complementares')], db_index=True, max_length=30),
        ),
    ]
