# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0006_relatoriotecnico_combustivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelotextorelatoriotecnico",
            name="campo",
            field=models.CharField(
                choices=[
                    ("motivo", "Descrição do evento"),
                    ("atividade", "Objetivo da participação"),
                    ("conclusao", "Conclusão"),
                    ("medidas", "Medidas a serem adotadas pelo órgão"),
                    ("info_complementares", "Informações complementares"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
