# Generated by Django 5.2.13 on 2026-06-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0008_backfill_prestacoes_por_servidor'),
        ('roteiros', '0004_roteiro_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diario_bordo', to='prestacoes_contas.prestacaocontas')),
            ],
            options={
                'verbose_name': 'Diário de Bordo',
                'verbose_name_plural': 'Diários de Bordo',
            },
        ),
        migrations.CreateModel(
            name='DiarioBordoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('abastecimento', models.BooleanField(blank=True, null=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='prestacoes_contas.diariobordo')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diario_bordo_trechos', to='roteiros.roteirotrecho')),
            ],
            options={
                'verbose_name': 'Trecho do diário de bordo',
                'verbose_name_plural': 'Trechos do diário de bordo',
                'ordering': ['diario', 'ordem', 'pk'],
            },
        ),
    ]
