# Generated by Django 5.2.13 on 2026-06-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0009_diariobordo_diariobordotrecho'),
        ('roteiros', '0004_roteiro_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='roteiro_ajustado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roteiros.roteiro'),
        ),
    ]
