# Generated by Django 5.2.13 on 2026-06-20 18:36

import django.core.validators
import prestacoes_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0010_prestacaocontas_roteiro_ajustado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='comprovante_saque_transferencia',
            field=models.FileField(blank=True, upload_to=prestacoes_contas.models.prestacao_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Comprovante de saque/transferência'),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='despacho_assinado',
            field=models.FileField(blank=True, upload_to=prestacoes_contas.models.prestacao_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Despacho assinado do ofício'),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='numero_solicitacao',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Número da solicitação'),
        ),
    ]
