# Generated by Codex on 2026-06-20

from pathlib import Path

import django.core.validators
import prestacoes_contas.models
from django.db import migrations, models
import django.db.models.deletion


def copiar_campos_legados_para_anexos(apps, schema_editor):
    PrestacaoContas = apps.get_model("prestacoes_contas", "PrestacaoContas")
    PrestacaoDocumentoAnexo = apps.get_model("prestacoes_contas", "PrestacaoDocumentoAnexo")

    campos = [
        ("despacho_assinado", "despacho"),
        ("comprovante_saque_transferencia", "comprovante"),
    ]
    for prestacao in PrestacaoContas.objects.all():
        update_fields = []
        for source_field, tipo in campos:
            field_file = getattr(prestacao, source_field, None)
            path = str(getattr(field_file, "name", "") or field_file or "").strip()
            if not path:
                continue
            PrestacaoDocumentoAnexo.objects.get_or_create(
                prestacao_id=prestacao.pk,
                tipo=tipo,
                arquivo=path,
                defaults={"nome_original": Path(path).name},
            )
            setattr(prestacao, source_field, "")
            update_fields.append(source_field)
        if update_fields:
            prestacao.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0011_prestacaocontas_comprovante_saque_transferencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestacaoDocumentoAnexo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("despacho", "Despacho assinado do ofício"), ("comprovante", "Comprovante de saque/transferência")], db_index=True, max_length=20)),
                ("arquivo", models.FileField(upload_to=prestacoes_contas.models.prestacao_documento_anexo_upload_to, validators=[django.core.validators.FileExtensionValidator(["pdf", "png", "jpg", "jpeg"])])),
                ("nome_original", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("prestacao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documentos_anexos", to="prestacoes_contas.prestacaocontas")),
            ],
            options={
                "verbose_name": "Anexo da prestação de contas",
                "verbose_name_plural": "Anexos da prestação de contas",
                "ordering": ["tipo", "criado_em", "pk"],
            },
        ),
        migrations.RunPython(copiar_campos_legados_para_anexos, noop_reverse),
    ]
