# Generated by Django 5.2.13 on 2026-06-21 16:46

import django.db.models.deletion
import prestacoes_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_configuracaosistema_pt_sufixo_numero'),
        ('prestacoes_contas', '0012_prestacaodocumentoanexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rt', 'Relatório Técnico'), ('db', 'Diário de Bordo')], db_index=True, max_length=4)),
                ('nome_esperado', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinada', 'Assinada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('link_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('link_criado_em', models.DateTimeField(blank=True, null=True)),
                ('link_expira_em', models.DateTimeField(blank=True, null=True)),
                ('identidade_confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('arquivo_origem', models.FileField(blank=True, upload_to=prestacoes_contas.models.assinatura_origem_upload_to)),
                ('modo', models.CharField(blank=True, choices=[('fonte', 'Fonte'), ('desenho', 'Desenho')], default='', max_length=10)),
                ('fonte', models.CharField(blank=True, default='', max_length=60)),
                ('assinatura_png', models.FileField(blank=True, upload_to=prestacoes_contas.models.assinatura_png_upload_to)),
                ('pagina', models.PositiveIntegerField(default=0)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('largura', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('arquivo_assinado', models.FileField(blank=True, upload_to=prestacoes_contas.models.assinatura_assinado_upload_to)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_ip', models.CharField(blank=True, default='', max_length=64)),
                ('codigo_verificacao', models.CharField(blank=True, default='', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='prestacoes_contas.prestacaocontas')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_documentos', to='cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Assinatura de documento',
                'verbose_name_plural': 'Assinaturas de documentos',
                'ordering': ['prestacao', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('prestacao', 'tipo'), name='uniq_assinatura_prestacao_tipo')],
            },
        ),
    ]
