# Generated by Django 5.2.15 on 2026-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0013_assinaturadocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturadocumento",
            name="hash_documento",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
