# Generated by Django 5.2.13 on 2026-07-09 19:55
#
# Reestrutura a prestação de contas: de "uma por servidor" para "uma por ofício",
# movendo o que é individual (número de solicitação, comprovante de saque e
# assinatura do RT) para o novo modelo ``PrestacaoServidor``.
#
# A ordem das operações é deliberada: primeiro criamos o modelo/os campos novos
# (nullable), removemos a constraint antiga de assinatura, rodamos a migração de
# dados que colapsa N prestações em 1 + N ``PrestacaoServidor`` e só então
# removemos os campos antigos e trocamos ``oficio`` para OneToOne.

import os
from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


# Campos de texto do RT usados para escolher a prestação "canônica" (a mais
# preenchida) quando o ofício não tem motorista entre os servidores.
_RT_TEXT_FIELDS = (
    "motivo", "atividade", "conclusao", "medidas", "info_complementares",
    "diaria", "translado", "combustivel", "passagem",
)


def colapsar_por_oficio(apps, schema_editor):
    PrestacaoContas = apps.get_model("prestacoes_contas", "PrestacaoContas")
    PrestacaoServidor = apps.get_model("prestacoes_contas", "PrestacaoServidor")
    PrestacaoDocumentoAnexo = apps.get_model("prestacoes_contas", "PrestacaoDocumentoAnexo")
    AssinaturaDocumento = apps.get_model("prestacoes_contas", "AssinaturaDocumento")
    RelatorioTecnico = apps.get_model("prestacoes_contas", "RelatorioTecnico")
    DiarioBordo = apps.get_model("prestacoes_contas", "DiarioBordo")
    Oficio = apps.get_model("oficios", "Oficio")

    grupos = defaultdict(list)
    for pc in PrestacaoContas.objects.all():
        grupos[pc.oficio_id].append(pc)

    # `BE-09`: `all_objects`, e não `objects`. O modelo histórico de migração só
    # conserva managers que sejam `_default_manager`, `_base_manager` ou
    # `use_in_migrations` (`db/migrations/state.py:905`). Como `objects` virou o
    # manager que recorta por área — e nenhum dos três —, ele deixa de existir
    # aqui. `all_objects` é o `_default_manager`, então sobrevive como `Manager`
    # puro: mesmo comportamento que `objects` tinha antes desta migração ser
    # escrita.
    motoristas = dict(Oficio.all_objects.values_list("pk", "motorista_id"))

    for oficio_id, prestacoes in grupos.items():
        motorista_id = motoristas.get(oficio_id)

        # `score` é consumido pelo `max()` logo abaixo, ainda dentro desta
        # iteração — `motorista_id` não muda entre definir e chamar.
        def score(pc):
            is_mot = 1 if (motorista_id and pc.servidor_id == motorista_id) else 0  # noqa: B023
            rt = RelatorioTecnico.objects.filter(prestacao=pc).first()
            rt_len = 0
            if rt is not None:
                rt_len = sum(len((getattr(rt, f, "") or "")) for f in _RT_TEXT_FIELDS)
            db_exists = 1 if DiarioBordo.objects.filter(prestacao=pc).exists() else 0
            return (is_mot, rt_len, db_exists, -pc.pk)

        canonical = max(prestacoes, key=score)
        outros = [pc for pc in prestacoes if pc.pk != canonical.pk]

        # ── Salvar artefatos compartilhados na canônica ──
        # Diário de bordo (1:1): se a canônica não tem, herda de outra prestação.
        if not DiarioBordo.objects.filter(prestacao=canonical).exists():
            db = DiarioBordo.objects.filter(prestacao__in=[pc.pk for pc in outros]).first()
            if db is not None:
                db.prestacao = canonical
                db.save()
        # Assinatura do Diário (nível ofício): idem.
        if not AssinaturaDocumento.objects.filter(prestacao=canonical, tipo="db").exists():
            db_sig = AssinaturaDocumento.objects.filter(
                prestacao__in=[pc.pk for pc in outros], tipo="db"
            ).first()
            if db_sig is not None:
                db_sig.prestacao = canonical
                db_sig.servidor_prestacao = None
                db_sig.save()
        # Despacho compartilhado: se a canônica está sem, herda o arquivo legado.
        if not (getattr(canonical, "despacho_assinado", None) and canonical.despacho_assinado.name):
            for pc in outros:
                nome = getattr(getattr(pc, "despacho_assinado", None), "name", "")
                if nome:
                    canonical.despacho_assinado = nome
                    canonical.save()
                    break

        # ── Um PrestacaoServidor por servidor, repontando o que é individual ──
        for pc in prestacoes:
            ps, _ = PrestacaoServidor.objects.get_or_create(
                prestacao=canonical,
                servidor_id=pc.servidor_id,
                defaults={"numero_solicitacao": pc.numero_solicitacao or ""},
            )
            if pc.numero_solicitacao and not ps.numero_solicitacao:
                ps.numero_solicitacao = pc.numero_solicitacao
                ps.save()

            # Comprovantes (anexos) → servidor.
            PrestacaoDocumentoAnexo.objects.filter(
                prestacao=pc, tipo="comprovante"
            ).update(servidor_prestacao=ps, prestacao=canonical)

            # Comprovante legado (FileField único) → vira anexo do servidor.
            legado = getattr(pc, "comprovante_saque_transferencia", None)
            nome_legado = getattr(legado, "name", "") if legado else ""
            if nome_legado and not PrestacaoDocumentoAnexo.objects.filter(
                servidor_prestacao=ps, tipo="comprovante", arquivo=nome_legado
            ).exists():
                PrestacaoDocumentoAnexo.objects.create(
                    prestacao=canonical,
                    servidor_prestacao=ps,
                    tipo="comprovante",
                    arquivo=nome_legado,
                    nome_original=os.path.basename(nome_legado),
                )

            # Assinatura do RT → servidor.
            AssinaturaDocumento.objects.filter(prestacao=pc, tipo="rt").update(
                servidor_prestacao=ps, prestacao=canonical
            )

        # ── Despacho (anexos) → canônica, sem duplicar por nome de arquivo ──
        vistos = set(
            PrestacaoDocumentoAnexo.objects.filter(
                prestacao=canonical, tipo="despacho"
            ).values_list("arquivo", flat=True)
        )
        for pc in outros:
            for anexo in PrestacaoDocumentoAnexo.objects.filter(prestacao=pc, tipo="despacho"):
                if anexo.arquivo and anexo.arquivo.name in vistos:
                    continue
                vistos.add(anexo.arquivo.name if anexo.arquivo else "")
                anexo.prestacao = canonical
                anexo.servidor_prestacao = None
                anexo.save()

        # ── Remover as prestações redundantes (dados individuais já preservados) ──
        for pc in outros:
            pc.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_configuracao_divisao_unidade_fk_ramal'),
        ('oficios', '0013_oficionumerolacuna'),
        ('prestacoes_contas', '0014_assinatura_cpf_completo_hash_documento'),
    ]

    operations = [
        # ── 1) Estruturas novas (aditivas) ──
        migrations.CreateModel(
            name='PrestacaoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao', models.CharField(blank=True, default='', max_length=60, verbose_name='Número da solicitação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor da prestação',
                'verbose_name_plural': 'Servidores da prestação',
                'ordering': ['prestacao', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='prestacaoservidor',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores_prestacao', to='prestacoes_contas.prestacaocontas'),
        ),
        migrations.AddField(
            model_name='prestacaoservidor',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_servidor', to='cadastros.servidor'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoservidor',
            constraint=models.UniqueConstraint(fields=('prestacao', 'servidor'), name='unique_servidor_por_prestacao'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='servidor_prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='prestacoes_contas.prestacaoservidor'),
        ),
        migrations.AddField(
            model_name='prestacaodocumentoanexo',
            name='servidor_prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='prestacoes_contas.prestacaoservidor'),
        ),

        # ── 2) Liberar a constraint antiga antes de repontar assinaturas ──
        migrations.RemoveConstraint(
            model_name='assinaturadocumento',
            name='uniq_assinatura_prestacao_tipo',
        ),

        # ── 3) Migração de dados: colapsar por ofício ──
        # As operações destrutivas de schema (remover campos, trocar oficio para
        # OneToOne) ficam na migração seguinte: o Postgres não permite ALTER TABLE
        # na mesma transação de um RunPython que mexeu nas linhas ("pending trigger
        # events"). Rodar em migração separada garante nova transação.
        migrations.RunPython(colapsar_por_oficio, migrations.RunPython.noop),
    ]
