# Generated by Django 5.2.13 on 2026-07-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_configuracao_divisao_unidade_fk_ramal'),
        ('prestacoes_contas', '0016_finaliza_reestrutura_por_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_manual_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_manual_nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_modo',
            field=models.CharField(choices=[('OFICIO', 'Manter motorista do ofício'), ('SERVIDOR', 'Outro servidor deste ofício'), ('OUTRO_OFICIO', 'Motorista de outro ofício')], default='OFICIO', max_length=16),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_oficio_referencia',
            field=models.CharField(blank=True, default='', help_text='Referência no formato número/ano (ex.: 15/2026).', max_length=16, verbose_name='Ofício do motorista'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_protocolo_ref',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo do motorista'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='motorista_servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='Motorista (servidor do ofício)'),
        ),
    ]
