# Generated by Django 5.2.16 on 2026-07-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0017_diariobordo_motorista_manual_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacaodocumentoanexo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("despacho", "Despacho assinado do ofício"),
                    ("comprovante", "Comprovante de saque/transferência"),
                    ("rt_assinado", "Relatório técnico assinado"),
                    ("db_assinado", "Diário de bordo assinado"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
