# Generated by Django 5.2.13 on 2026-07-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_configuracao_divisao_unidade_fk_ramal'),
        ('prestacoes_contas', '0018_alter_prestacaodocumentoanexo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariobordo',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viatura', verbose_name='Viatura (cadastro)'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viatura_manual_combustivel',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viatura_manual_modelo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viatura_manual_placa',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viatura_manual_tipo',
            field=models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viatura_modo',
            field=models.CharField(choices=[('OFICIO', 'Manter a viatura do ofício'), ('BANCO', 'Selecionar do cadastro'), ('MANUAL', 'Preencher manualmente')], default='OFICIO', max_length=10),
        ),
    ]
