# Generated by Django 5.2.16 on 2026-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0020_prestacaocontas_arquivada_finalizada"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaoservidor",
            name="diaria_valor_override",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Diária deste servidor (se for diferente)",
            ),
        ),
    ]
