# Generated by Django 5.2.13 on 2026-07-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0015_remove_oficio_oficios_oficio_ano_numero_unique_and_more'),
        ('prestacoes_contas', '0021_prestacaoservidor_diaria_valor_override'),
        ('roteiros', '0007_roteiro_area'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_contas', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddIndex(
            model_name='prestacaocontas',
            index=models.Index(fields=['area', '-criado_em'], name='prestacoes_area_criado_idx'),
        ),
    ]
