# Generated by Django 5.2.13 on 2026-07-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0022_prestacaocontas_area_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelotextorelatoriotecnico',
            name='unique_modelo_texto_rt_campo_nome',
        ),
        migrations.AddField(
            model_name='modelotextorelatoriotecnico',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_texto_relatorio_tecnico', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddIndex(
            model_name='modelotextorelatoriotecnico',
            index=models.Index(fields=['area', 'campo', 'ordem', 'nome'], name='prest_rt_txt_area_campo_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelotextorelatoriotecnico',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('campo', 'nome'), name='unique_modelo_texto_rt_campo_nome'),
        ),
        migrations.AddConstraint(
            model_name='modelotextorelatoriotecnico',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'campo', 'nome'), name='prest_rt_texto_area_campo_nome_unique'),
        ),
    ]
