# Generated by Django 5.2.13 on 2026-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0023_remove_modelotextorelatoriotecnico_unique_modelo_texto_rt_campo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoservidor',
            name='prazo_limite_saque',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo limite para saque'),
        ),
    ]
