# Generated by Django 5.2.16 on 2026-07-27 18:46

import core.uploads
import prestacoes_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0027_assinatura_token_protegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaodocumentoanexo',
            name='arquivo',
            field=models.FileField(upload_to=prestacoes_contas.models.prestacao_documento_anexo_upload_to, validators=[core.uploads.validate_private_document_upload]),
        ),
    ]
