# Generated by Django 5.2.17 on 2026-08-06 18:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prestacoes_contas", "0030_diaria_valor_recebido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelotextorelatoriotecnico",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["campo", "ordem", "nome"],
                "verbose_name": "Modelo de texto do RT",
                "verbose_name_plural": "Modelos de texto do RT",
            },
        ),
        migrations.AlterModelOptions(
            name="prestacaocontas",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-criado_em"],
                "verbose_name": "Prestação de Contas",
                "verbose_name_plural": "Prestações de Contas",
            },
        ),
        migrations.AlterModelManagers(
            name="modelotextorelatoriotecnico",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="prestacaocontas",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
