# Generated by Django 5.2.16 on 2026-08-22 19:09

import django.db.models.deletion
import prestacoes_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacoes_contas', '0036_novo116_mensagem_do_km_do_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaodocumentoanexo',
            name='arquivo_original',
            field=models.FileField(blank=True, help_text='PDF como enviado, antes do carimbo. Origem de todo recarimbo.', upload_to=prestacoes_contas.models.prestacao_anexo_original_upload_to),
        ),
        migrations.CreateModel(
            name='CarimboSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.PositiveSmallIntegerField(default=0)),
                ('x', models.FloatField(help_text='Fração da largura, 0 = borda esquerda.')),
                ('y', models.FloatField(help_text='Fração da altura, 0 = topo da página.')),
                ('tamanho', models.FloatField(default=0.012)),
                ('ajustado_manualmente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='prestacoes_contas.prestacaodocumentoanexo')),
                ('servidor_prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos_solicitacao', to='prestacoes_contas.prestacaoservidor')),
            ],
            options={
                'verbose_name': 'Carimbo do número de solicitação',
                'verbose_name_plural': 'Carimbos do número de solicitação',
                'ordering': ['pagina', 'y', 'x', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('anexo', 'servidor_prestacao'), name='carimbo_unico_por_servidor_no_anexo')],
            },
        ),
    ]
