# Generated by Django 5.2.15 on 2026-06-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("google_drive", "0003_drive_credenciais_pasta_raiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveArquivoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "campo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nome do FileField de origem (vazio quando o modelo tem um único arquivo).",
                        max_length=64,
                    ),
                ),
                ("file_id", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("nome", models.CharField(blank=True, max_length=255)),
                ("pasta_id", models.CharField(blank=True, default="", max_length=200)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("mock", models.BooleanField(default=False)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo externo no Drive",
                "verbose_name_plural": "Arquivos externos no Drive",
                "ordering": ["-enviado_em"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="google_driv_content_6586ca_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "campo"),
                        name="drive_arquivo_externo_unico_por_campo",
                    )
                ],
            },
        ),
    ]
