# Generated by Django 5.2.15 on 2026-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_drive", "0004_drivearquivoexterno"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivearquivo",
            name="atalho_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="drivearquivo",
            name="atalho_pasta_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="drivearquivoexterno",
            name="atalho_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="drivearquivoexterno",
            name="atalho_pasta_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
