# Generated by Django 5.2.15 on 2026-06-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "google_drive",
            "0005_drivearquivo_atalho_id_drivearquivo_atalho_pasta_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveReorganizacaoJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                            ("erro", "Erro"),
                        ],
                        db_index=True,
                        default="em_andamento",
                        max_length=20,
                    ),
                ),
                ("total_eventos", models.PositiveIntegerField(default=0)),
                ("eventos_processados", models.PositiveIntegerField(default=0)),
                ("avulsos", models.PositiveIntegerField(default=0)),
                ("erros", models.PositiveIntegerField(default=0)),
                ("mensagem", models.TextField(blank=True, default="")),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Job de reorganização do Drive",
                "verbose_name_plural": "Jobs de reorganização do Drive",
                "ordering": ["-iniciado_em"],
            },
        ),
    ]
