# Generated by Django 5.2.13 on 2026-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0006_drivereorganizacaojob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivearquivo',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drivearquivoexterno',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
