# Generated by Django 5.2.15 on 2026-07-04 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("google_drive", "0007_alter_drivearquivo_mime_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("tentativas", models.PositiveIntegerField(default=1)),
                ("ultimo_erro", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendência de sincronização com o Drive",
                "verbose_name_plural": "Pendências de sincronização com o Drive",
                "ordering": ["-atualizado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"),
                        name="drive_sync_status_unico",
                    )
                ],
            },
        ),
    ]
