# Generated by Django 5.2.13 on 2026-07-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0008_drivesyncstatus'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivecredenciais',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_credenciais', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
    ]
