# Generated by Django 5.2.13 on 2026-07-15 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0008_drivesyncstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivecredenciais',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_credenciais', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
