# Generated by Django 5.2.13 on 2026-07-15 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0009_drivecredenciais_usuario'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivereorganizacaojob',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_jobs_reorganizacao', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='drivereorganizacaojob',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_jobs_reorganizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='drivesyncstatus',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_pendencias_sync', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='drivereorganizacaojob',
            index=models.Index(fields=['usuario', 'area', 'status'], name='drive_job_usuario_area_idx'),
        ),
    ]
