# Generated by Django 5.2.17 on 2026-08-06 20:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google_drive", "0011_criptografa_tokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drivereorganizacaojob",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-iniciado_em"],
                "verbose_name": "Job de reorganização do Drive",
                "verbose_name_plural": "Jobs de reorganização do Drive",
            },
        ),
        migrations.AlterModelManagers(
            name="drivereorganizacaojob",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
