# Generated by Django 5.2.13 on 2026-05-08 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('roteiros', '0003_roteiro_mapa_openrouteservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data_criacao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('assunto', models.CharField(blank=True, default='', max_length=255)),
                ('motivo', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('custeio', models.CharField(choices=[('UNIDADE_DPC', 'Unidade DPC'), ('OUTRA_INSTITUICAO', 'Outra instituição'), ('ONUS_LIMITADO', 'Ônus limitado')], default='UNIDADE_DPC', max_length=30)),
                ('custeio_observacao', models.CharField(blank=True, default='', max_length=255)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_motorista', to='cadastros.servidor')),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='roteiros.roteiro')),
                ('servidores', models.ManyToManyField(blank=True, related_name='oficios', to='cadastros.servidor')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.unidade')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='cadastros.viatura')),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-data_criacao', '-created_at'],
            },
        ),
    ]
