# Generated by Django 5.2.13 on 2026-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('oficios', '0001_initial'),
        ('roteiros', '0003_roteiro_mapa_openrouteservice'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('ano', 'numero'), name='oficios_oficio_ano_numero_unique'),
        ),
    ]
