# Generated by Django 5.2.13 on 2026-05-08 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_oficio_oficios_oficio_ano_numero_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMotivoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('is_padrao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modelo de motivo de ofício',
                'verbose_name_plural': 'Modelos de motivo de ofício',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado'), ('FINALIZADO', 'Finalizado (legado)'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20),
        ),
    ]
