# Generated by Django 5.2.13 on 2026-05-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_configuracaosistema_colunas_faltantes'),
        ('oficios', '0003_modelomotivooficio_alter_oficio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_cargo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_rg',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_manual_unidade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_modo',
            field=models.CharField(choices=[('SERVIDOR', 'Servidor'), ('MANUAL', 'Manual')], default='SERVIDOR', max_length=10),
        ),
        migrations.AddField(
            model_name='oficio',
            name='porte_transporte_armas',
            field=models.BooleanField(default=True, verbose_name='Porte/transporte de armas'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='transporte_combustivel_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.combustivel'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='transporte_modelo_manual',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='oficio',
            name='transporte_placa_manual',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='oficio',
            name='transporte_tipo_manual',
            field=models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='', max_length=20),
        ),
    ]
