# Generated by Django 5.2.13 on 2026-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0004_oficio_transporte_motorista_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_referencia',
            field=models.CharField(blank=True, default='', help_text='Referência no formato número/ano (ex.: 15/2026).', max_length=16, verbose_name='Ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_protocolo_ref',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo do motorista'),
        ),
    ]
