# Generated by Django 5.2.13 on 2026-05-12 18:58

from django.db import migrations
from django.db import models


def copiar_servidores_para_termos(apps, schema_editor):
    Oficio = apps.get_model("oficios", "Oficio")
    for oficio in Oficio.objects.all().iterator():
        oficio.servidores_termo_autorizacao.set(oficio.servidores.all())


def limpar_servidores_termo(apps, schema_editor):
    Oficio = apps.get_model("oficios", "Oficio")
    for oficio in Oficio.objects.all().iterator():
        oficio.servidores_termo_autorizacao.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0011_configuracaosistema_colunas_faltantes"),
        ("oficios", "0006_oficio_retificado_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficio",
            name="servidores_termo_autorizacao",
            field=models.ManyToManyField(
                blank=True,
                related_name="oficios_termo_autorizacao",
                to="cadastros.servidor",
                verbose_name="Servidores com Termo de Autorização",
            ),
        ),
        migrations.RunPython(copiar_servidores_para_termos, limpar_servidores_termo),
    ]
