# Generated by Django 5.2.13 on 2026-06-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('oficios', '0007_oficio_servidores_termo_autorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='eventos.evento'),
        ),
    ]
