# Generated by Django 5.2.16 on 2026-07-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oficios", "0012_alter_oficio_evento"),
    ]

    operations = [
        migrations.CreateModel(
            name="OficioNumeroLacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("numero", models.PositiveIntegerField()),
                ("liberado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Número de ofício liberado",
                "verbose_name_plural": "Números de ofício liberados",
                "ordering": ["ano", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ano", "numero"),
                        name="oficios_lacuna_ano_numero_unique",
                    )
                ],
            },
        ),
    ]
