# Generated by Django 5.2.16 on 2026-07-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oficios", "0013_oficionumerolacuna"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficio",
            name="destino_gabinete",
            field=models.CharField(
                choices=[
                    ("ADJUNTO", "Gabinete do Delegado-Geral Adjunto"),
                    ("GERAL", "Gabinete do Delegado-Geral"),
                ],
                default="ADJUNTO",
                help_text="Autoridade a quem o ofício é endereçado quando o destino é dentro do Paraná.",
                max_length=10,
                verbose_name="Gabinete de destino",
            ),
        ),
    ]
