# Generated by Django 5.2.16 on 2026-07-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oficios", "0014_oficio_complementar_documento"),
        ("oficios", "0014_oficio_destino_gabinete"),
    ]

    operations = []
