# Generated by Django 5.2.13 on 2026-07-15 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_configuracaosistema_area'),
        ('eventos', '0010_evento_area_evento_eventos_evento_area_criado_idx'),
        ('oficios', '0014_oficio_complementar_documento'),
        ('roteiros', '0006_alter_roteiro_evento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oficio',
            name='oficios_oficio_ano_numero_unique',
        ),
        migrations.RemoveConstraint(
            model_name='oficionumerolacuna',
            name='oficios_lacuna_ano_numero_unique',
        ),
        migrations.AddField(
            model_name='oficio',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddField(
            model_name='oficionumerolacuna',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficio_lacunas', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('area', 'ano', 'numero'), name='oficios_oficio_area_ano_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='oficionumerolacuna',
            constraint=models.UniqueConstraint(fields=('area', 'ano', 'numero'), name='oficios_lacuna_area_ano_numero_unique'),
        ),
    ]
