# Generated by Django 5.2.13 on 2026-07-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0015_remove_oficio_oficios_oficio_ano_numero_unique_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelomotivooficio',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_motivo_oficio', to='usuarios.areatrabalho', verbose_name='Area de trabalho'),
        ),
        migrations.AlterField(
            model_name='modelomotivooficio',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='modelomotivooficio',
            index=models.Index(fields=['area', 'ordem', 'nome'], name='oficios_motivo_area_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivooficio',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('nome',), name='oficios_motivo_nome_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivooficio',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nome'), name='oficios_motivo_area_nome_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivooficio',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False), ('is_padrao', True)), fields=('area',), name='oficios_motivo_area_padrao_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelomotivooficio',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True), ('is_padrao', True)), fields=('is_padrao',), name='oficios_motivo_global_padrao_unique'),
        ),
    ]
