# Generated by Django 5.2.17 on 2026-08-06 18:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oficios", "0017_configuracaonumeracaooficio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaonumeracaooficio",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-ano", "area_id"],
            },
        ),
        migrations.AlterModelOptions(
            name="modelomotivooficio",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ordem", "nome"],
                "verbose_name": "Modelo de motivo de ofício",
                "verbose_name_plural": "Modelos de motivo de ofício",
            },
        ),
        migrations.AlterModelOptions(
            name="oficio",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-data_criacao", "-created_at"],
                "verbose_name": "Ofício",
                "verbose_name_plural": "Ofícios",
            },
        ),
        migrations.AlterModelOptions(
            name="oficionumerolacuna",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["ano", "numero"],
                "verbose_name": "Número de ofício liberado",
                "verbose_name_plural": "Números de ofício liberados",
            },
        ),
        migrations.AlterModelManagers(
            name="configuracaonumeracaooficio",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="modelomotivooficio",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="oficio",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="oficionumerolacuna",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
